<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateMuncityTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return vo
     */
       public function up()
    {
           Schema::create('muncity', function (Blueprint $table) {
            
            
            $table->increments('id');
             $table->string('code');
         
            $table->string('muncity');
        });

        DB::table('muncity')
      ->insert([
        ['code' => '32', 'Muncity' => 'ADAMS'],
        ['code' => '146', 'Muncity' => 'BACARRA'],
        ['code' => '34', 'Muncity' => 'BADOC'],
        ['code' => '35', 'Muncity' => 'BANGUI'],
        ['code' => '36', 'Muncity' => 'BATAC'],
        ['code' => '37', 'Muncity' => 'BURGOS'],
        ['code' => '38', 'Muncity' => 'CARASI'],
        ['code' => '39', 'Muncity' => 'CURRIMAO'],
        ['code' => '30', 'Muncity' => 'DINGRAS'],
        ['code' => '136', 'Muncity' => 'DUMALNEG'],
        ['code' => '137', 'Muncity' => 'BANNA (ESPIRITU)'],
        ['code' => '138', 'Muncity' => 'LAOAG CITY (Capital)'],
        ['code' => '139', 'Muncity' => 'MARCOS'],
        ['code' => '140', 'Muncity' => 'NUEVA ERA'],
        ['code' => '141', 'Muncity' => 'PAGUDPUD'],
        ['code' => '142', 'Muncity' => 'PAOAY'],
        ['code' => '143', 'Muncity' => 'PASUQUIN'],
        ['code' => '144', 'Muncity' => 'PDIG'],
        ['code' => '145', 'Muncity' => 'PINILI'],
        ['code' => '21', 'Muncity' => 'SAN NICOLAS'],
        ['code' => '22', 'Muncity' => 'SARRAT'],
        ['code' => '23', 'Muncity' => 'SOLSONA'],
        ['code' => '24', 'Muncity' => 'VINTAR'],
        ['code' => '25', 'Muncity' => 'ALILEM'],
        ['code' => '26', 'Muncity' => 'BANAYOYO'],
        ['code' => '27', 'Muncity' => 'BANTAY'],
        ['code' => '28', 'Muncity' => 'BURGOS'],
        ['code' => '29', 'Muncity' => 'CABUGAO'],
        ['code' => '40', 'Muncity' => 'CITY OF CANDON'],
        ['code' => '41', 'Muncity' => 'CAOAYAN'],
        ['code' => '42', 'Muncity' => 'CERVANTES'],
        ['code' => '43', 'Muncity' => 'GALIMUYOD'],
        ['code' => '44', 'Muncity' => 'GREGORIO DEL PILAR (CONCEPCION)'],
        ['code' => '45', 'Muncity' => 'LLDA'],
        ['code' => '46', 'Muncity' => 'MAGSINGAL'],
        ['code' => '47', 'Muncity' => 'NAGBUKEL'],
        ['code' => '48', 'Muncity' => 'NARVACAN'],
        ['code' => '49', 'Muncity' => 'QUIRINO (ANGKAKI)'],
        ['code' => '50', 'Muncity' => 'SALCEDO (BAUGEN)'],
        ['code' => '51', 'Muncity' => 'SAN EMILIO'],
        ['code' => '52', 'Muncity' => 'SAN ESTEBAN'],
        ['code' => '53', 'Muncity' => 'SAN ILDEFONSO'],
        ['code' => '54', 'Muncity' => 'SAN JUAN (LAPOG)'],
        ['code' => '55', 'Muncity' => 'SAN VICENTE'],
        ['code' => '56', 'Muncity' => 'SANTA'],
        ['code' => '57', 'Muncity' => 'SANTA CATALINA'],
        ['code' => '58', 'Muncity' => 'SANTA CRUZ'],
        ['code' => '59', 'Muncity' => 'SANTA LUCIA'],
        ['code' => '60', 'Muncity' => 'SANTA MARIA'],
        ['code' => '61', 'Muncity' => 'SANTIAGO'],
        ['code' => '63', 'Muncity' => 'SANTO DOMINGO'],
        ['code' => '62', 'Muncity' => 'SIGAY'],
        ['code' => '64', 'Muncity' => 'SINAIT'],
        ['code' => '65', 'Muncity' => 'SUGPON'],
        ['code' => '66', 'Muncity' => 'SUYO'],
        ['code' => '67', 'Muncity' => 'TAGUDIN'],
        ['code' => '68', 'Muncity' => 'CITY OF VIGAN (Capital)'],
        ['code' => '69', 'Muncity' => 'AGOO'],
        ['code' => '70', 'Muncity' => 'ARINGAY'],
        ['code' => '71', 'Muncity' => 'BACNOTAN'],
        ['code' => '72', 'Muncity' => 'BAGULIN'],
        ['code' => '73', 'Muncity' => 'BALAOAN'],
        ['code' => '74', 'Muncity' => 'BANGAR'],
        ['code' => '75', 'Muncity' => 'BAUANG'],
        ['code' => '76', 'Muncity' => 'BURGOS'],
        ['code' => '77', 'Muncity' => 'CABA'],
        ['code' => '78', 'Muncity' => 'LUNA'],
        ['code' => '79', 'Muncity' => 'NAGUILIAN'],
        ['code' => '80', 'Muncity' => 'PUGO'],
        ['code' => '81', 'Muncity' => 'ROSARIO'],
        ['code' => '82', 'Muncity' => 'CITY OF SAN FERNANDO (Capital)'],
        ['code' => '83', 'Muncity' => 'SAN GABRIEL'],
        ['code' => '84', 'Muncity' => 'SAN JUAN'],
        ['code' => '85', 'Muncity' => 'SANTO TOMAS'],
        ['code' => '86', 'Muncity' => 'SANTOL'],
        ['code' => '87', 'Muncity' => 'SUDIPEN'],
        ['code' => '88', 'Muncity' => 'TUBAO'],
        ['code' => '89', 'Muncity' => 'AGNO'],
        ['code' => '90', 'Muncity' => 'AGUILAR'],
        ['code' => '91', 'Muncity' => 'CITY OF ALAMINOS'],
        ['code' => '92', 'Muncity' => 'ALCALA'],
        ['code' => '148', 'Muncity' => 'ANDA'],
        ['code' => '93', 'Muncity' => 'ASINGAN'],
        ['code' => '94', 'Muncity' => 'BALUNGAO'],
        ['code' => '95', 'Muncity' => 'BANI'],
        ['code' => '96', 'Muncity' => 'BASISTA'],
        ['code' => '97', 'Muncity' => 'BAUTISTA'],
        ['code' => '98', 'Muncity' => 'BAYAMBANG'],
        ['code' => '99', 'Muncity' => 'BINALONAN'],
        ['code' => '100', 'Muncity' => 'BINMALEY'],
        ['code' => '101', 'Muncity' => 'BOLINAO'],
        ['code' => '102', 'Muncity' => 'BUGALLON'],
        ['code' => '103', 'Muncity' => 'BURGOS'],
        ['code' => '104', 'Muncity' => 'CALASIAO'],
        ['code' => '105', 'Muncity' => 'DAGUPAN CITY'],
        ['code' => '106', 'Muncity' => 'DASOL'],
        ['code' => '107', 'Muncity' => 'INFANTA'],
        ['code' => '108', 'Muncity' => 'LABRADOR'],
        ['code' => '109', 'Muncity' => 'LINGAYEN (Capital)'],
        ['code' => '110', 'Muncity' => 'MABINI'],
        ['code' => '111', 'Muncity' => 'MALASIQUI'],
        ['code' => '112', 'Muncity' => 'MANAOAG'],
        ['code' => '113', 'Muncity' => 'MANGALDAN'],
        ['code' => '114', 'Muncity' => 'MANGATAREM'],
        ['code' => '115', 'Muncity' => 'MAPANDAN'],
        ['code' => '116', 'Muncity' => 'NATIVAD'],
        ['code' => '117', 'Muncity' => 'POZZORUBIO'],
        ['code' => '118', 'Muncity' => 'ROSALES'],
        ['code' => '119', 'Muncity' => 'SAN CARLOS CITY'],
        ['code' => '120', 'Muncity' => 'SAN FABIAN'],
        ['code' => '121', 'Muncity' => 'SAN JACINTO'],
        ['code' => '122', 'Muncity' => 'SAN MANUEL'],
        ['code' => '123', 'Muncity' => 'SAN NICOLAS'],
        ['code' => '124', 'Muncity' => 'SAN QUINTIN'],
        ['code' => '125', 'Muncity' => 'SANTA BARBARA'],
        ['code' => '126', 'Muncity' => 'SANTA MARIA'],
        ['code' => '127', 'Muncity' => 'SANTO TOMAS'],
        ['code' => '128', 'Muncity' => 'SISON'],
        ['code' => '129', 'Muncity' => 'SUAL'],
        ['code' => '130', 'Muncity' => 'TAYUG'],
        ['code' => '131', 'Muncity' => 'UMINGAN'],
        ['code' => '132', 'Muncity' => 'URBIZTONDO'],
        ['code' => '133', 'Muncity' => 'CITY OF URDANETA'],
        ['code' => '135', 'Muncity' => 'VILLASIS'],
        ['code' => '134', 'Muncity' => 'LAOAC'],
        ['code' => '200', 'Muncity' => 'BASCO (Capital)'],
        ['code' => '201', 'Muncity' => 'ITBAYAT'],
        ['code' => '203', 'Muncity' => 'IVANA'],
        ['code' => '02', 'Muncity' => 'MAHATAO'],
        ['code' => '02', 'Muncity' => 'SABTANG'],
        ['code' => '02', 'Muncity' => 'UYUGAN'],
        ['code' => '02', 'Muncity' => 'ABULUG'],
        ['code' => '02', 'Muncity' => 'ALCALA'],
        ['code' => '02', 'Muncity' => 'ALLACAPAN'],
        ['code' => '02', 'Muncity' => 'AMULUNG'],
        ['code' => '02', 'Muncity' => 'APARRI'],
        ['code' => '02', 'Muncity' => 'BAGGAO'],
        ['code' => '02', 'Muncity' => 'BALLESTEROS'],
        ['code' => '02', 'Muncity' => 'BUGUEY'],
        ['code' => '02', 'Muncity' => 'CALAYAN'],
        ['code' => '02', 'Muncity' => 'CAMALANIUGAN'],
        ['code' => '02', 'Muncity' => 'CLAVERIA'],
        ['code' => '02', 'Muncity' => 'ENRILE'],
        ['code' => '02', 'Muncity' => 'GATTARAN'],
        ['code' => '02', 'Muncity' => 'GONZAGA'],
        ['code' => '02', 'Muncity' => 'IGUIG'],
        ['code' => '02', 'Muncity' => 'LAL-LO'],
        ['code' => '02', 'Muncity' => 'LASAM'],
        ['code' => '02', 'Muncity' => 'PAMPLONA'],
        ['code' => '02', 'Muncity' => 'PEÑABLANCA'],
        ['code' => '02', 'Muncity' => 'PIAT'],
        ['code' => '02', 'Muncity' => 'RIZAL'],
        ['code' => '02', 'Muncity' => 'SANCHEZ-MIRA'],
        ['code' => '02', 'Muncity' => 'SANTA ANA'],
        ['code' => '02', 'Muncity' => 'SANTA PRAXEDES'],
        ['code' => '02', 'Muncity' => 'SANTA TERESITA'],
        ['code' => '02', 'Muncity' => 'SANTO NIÑO (FAIRE)'],
        ['code' => '02', 'Muncity' => 'SOLANA'],
        ['code' => '02', 'Muncity' => 'TUAO'],
        ['code' => '02', 'Muncity' => 'TUGUEGARAO CITY(Capital)'],
        ['code' => '02', 'Muncity' => 'ALICIA'],
        ['code' => '02', 'Muncity' => 'ANGADANAN'],
        ['code' => '02', 'Muncity' => 'AURORA'],
        ['code' => '02', 'Muncity' => 'BENITO SOLIVEN'],
        ['code' => '02', 'Muncity' => 'BURGOS'],
        ['code' => '02', 'Muncity' => 'CABAGAN'],
        ['code' => '02', 'Muncity' => 'CABATUAN'],
        ['code' => '02', 'Muncity' => 'CITY OF CAUAYAN'],
        ['code' => '02', 'Muncity' => 'CORDON'],
        ['code' => '02', 'Muncity' => 'DINAPIGUE'],
        ['code' => '02', 'Muncity' => 'DIVILICAN'],
        ['code' => '02', 'Muncity' => 'ECHAGUE'],
        ['code' => '02', 'Muncity' => 'GAMU'],
        ['code' => '02', 'Muncity' => 'ILAGAN (Capital)'],
        ['code' => '02', 'Muncity' => 'JONES'],
        ['code' => '02', 'Muncity' => 'LUNA'],
        ['code' => '02', 'Muncity' => 'MACONACON'],
        ['code' => '02', 'Muncity' => 'DELFIN ALBANO (MAGSAYSAY)'],
        ['code' => '02', 'Muncity' => 'MALLIG'],
        ['code' => '02', 'Muncity' => 'NAGUILIAN'],
        ['code' => '02', 'Muncity' => 'PALANAN'],
        ['code' => '02', 'Muncity' => 'QUEZON'],
        ['code' => '02', 'Muncity' => 'QUIRINO'],
        ['code' => '02', 'Muncity' => 'RAMON'],
        ['code' => '02', 'Muncity' => 'REINA MERCEDES'],
        ['code' => '02', 'Muncity' => 'ROXAS'],
        ['code' => '02', 'Muncity' => 'SAN AGUSTIN'],
        ['code' => '02', 'Muncity' => 'SAN GUILLERMO'],
        ['code' => '02', 'Muncity' => 'SAN ISRO'],
        ['code' => '02', 'Muncity' => 'SAN MANUEL'],
        ['code' => '02', 'Muncity' => 'SAN MARIANO'],
        ['code' => '02', 'Muncity' => 'SAN MATEO'],
        ['code' => '02', 'Muncity' => 'SAN PABLO'],
        ['code' => '02', 'Muncity' => 'SANTA MARIA'],
        ['code' => '02', 'Muncity' => 'CITY OF SANTIAGO'],
        ['code' => '02', 'Muncity' => 'SANTO TOMAS'],
        ['code' => '02', 'Muncity' => 'TUMAUINI'],
        ['code' => '02', 'Muncity' => 'AMBAGUIO'],
        ['code' => '02', 'Muncity' => 'ARITAO'],
        ['code' => '02', 'Muncity' => 'BAGABAG'],
        ['code' => '02', 'Muncity' => 'BAMBANG'],
        ['code' => '02', 'Muncity' => 'BAYOMBONG (Capital)'],
        ['code' => '02', 'Muncity' => 'DIADI'],
        ['code' => '02', 'Muncity' => 'DUPAX DEL NORTE'],
        ['code' => '02', 'Muncity' => 'DUPAX DEL SUR'],
        ['code' => '02', 'Muncity' => 'KASIBU'],
        ['code' => '02', 'Muncity' => 'KAYAPA'],
        ['code' => '02', 'Muncity' => 'QUEZON'],
        ['code' => '02', 'Muncity' => 'SANTA FE'],
        ['code' => '02', 'Muncity' => 'SOLANO'],
        ['code' => '02', 'Muncity' => 'VILLAVERDE'],
        ['code' => '02', 'Muncity' => 'ALFONSO CASTAÑEDA'],
        ['code' => '02', 'Muncity' => 'AGLIPAY'],
        ['code' => '02', 'Muncity' => 'CABARROGUIS (Capital)'],
        ['code' => '02', 'Muncity' => 'DIFFUN'],
        ['code' => '02', 'Muncity' => 'MADDELA'],
        ['code' => '02', 'Muncity' => 'SAGUDAY'],
        ['code' => '02', 'Muncity' => 'NAGTIPUNAN'],
        ['code' => '03', 'Muncity' => 'ABUCAY'],
        ['code' => '03', 'Muncity' => 'BAGAC'],
        ['code' => '03', 'Muncity' => 'CITY OF BALANGA (Capital)'],
        ['code' => '03', 'Muncity' => 'DINALUPIHAN'],
        ['code' => '03', 'Muncity' => 'HERMOSA'],
        ['code' => '03', 'Muncity' => 'LIMAY'],
        ['code' => '03', 'Muncity' => 'MARIVELES'],
        ['code' => '03', 'Muncity' => 'MORONG'],
        ['code' => '03', 'Muncity' => 'ORANI'],
        ['code' => '03', 'Muncity' => 'ORION'],
        ['code' => '03', 'Muncity' => 'PILAR'],
        ['code' => '03', 'Muncity' => 'SAMAL'],
        ['code' => '03', 'Muncity' => 'ANGAT'],
        ['code' => '03', 'Muncity' => 'BALAGTAS (BIGAA)'],
        ['code' => '03', 'Muncity' => 'BALIUAG'],
        ['code' => '03', 'Muncity' => 'BOCAUE'],
        ['code' => '03', 'Muncity' => 'BULACAN'],
        ['code' => '03', 'Muncity' => 'BUSTOS'],
        ['code' => '03', 'Muncity' => 'CALUMPIT'],
        ['code' => '03', 'Muncity' => 'GUIGUINTO'],
        ['code' => '03', 'Muncity' => 'HAGONOY'],
        ['code' => '03', 'Muncity' => 'CITY OF MALOLOS (Capital)'],
        ['code' => '03', 'Muncity' => 'MARILAO'],
        ['code' => '03', 'Muncity' => 'MEYCAUAYAN'],
        ['code' => '03', 'Muncity' => 'NORZAGARAY'],
        ['code' => '03', 'Muncity' => 'OBANDO'],
        ['code' => '03', 'Muncity' => 'PANDI'],
        ['code' => '03', 'Muncity' => 'PAOMBONG'],
        ['code' => '03', 'Muncity' => 'PLAREL'],
        ['code' => '03', 'Muncity' => 'PULILAN'],
        ['code' => '03', 'Muncity' => 'SAN ILDEFONSO'],
        ['code' => '03', 'Muncity' => 'CITY OF SAN JOSE DEL MONTE'],
        ['code' => '03', 'Muncity' => 'SAN MIGUEL'],
        ['code' => '03', 'Muncity' => 'SAN RAFAEL'],
        ['code' => '03', 'Muncity' => 'SANTA MARIA'],
        ['code' => '03', 'Muncity' => 'DOÑA REMEDIOS TRINAD'],
        ['code' => '03', 'Muncity' => 'ALIAGA'],
        ['code' => '03', 'Muncity' => 'BONGABON'],
        ['code' => '03', 'Muncity' => 'CABANATUAN CITY'],
        ['code' => '03', 'Muncity' => 'CABIAO'],
        ['code' => '03', 'Muncity' => 'CARRANGLAN'],
        ['code' => '03', 'Muncity' => 'CUYAPO'],
        ['code' => '03', 'Muncity' => 'GABALDON (BITULOK & SABANI)'],
        ['code' => '03', 'Muncity' => 'CITY OF GAPAN'],
        ['code' => '03', 'Muncity' => 'GENERAL MAMERTO NATIVAD'],
        ['code' => '03', 'Muncity' => 'GENERAL TINIO (PAPAYA)'],
        ['code' => '03', 'Muncity' => 'GUIMBA'],
        ['code' => '03', 'Muncity' => 'JAEN'],
        ['code' => '03', 'Muncity' => 'LAUR'],
        ['code' => '03', 'Muncity' => 'LICAB'],
        ['code' => '03', 'Muncity' => 'LLANERA'],
        ['code' => '03', 'Muncity' => 'LUPAO'],
        ['code' => '03', 'Muncity' => 'SCIENCE CITY OF MUÑOZ'],
        ['code' => '03', 'Muncity' => 'NAMPICUAN'],
        ['code' => '03', 'Muncity' => 'PALAYAN CITY (Capital)'],
        ['code' => '03', 'Muncity' => 'PANTABANGAN'],
        ['code' => '03', 'Muncity' => 'PEÑARANDA'],
        ['code' => '03', 'Muncity' => 'QUEZON'],
        ['code' => '03', 'Muncity' => 'RIZAL'],
        ['code' => '03', 'Muncity' => 'SAN ANTONIO'],
        ['code' => '03', 'Muncity' => 'SAN ISRO'],
        ['code' => '03', 'Muncity' => 'SAN JOSE CITY'],
        ['code' => '03', 'Muncity' => 'SAN LEONARDO'],
        ['code' => '03', 'Muncity' => 'SANTA ROSA'],
        ['code' => '03', 'Muncity' => 'SANTO DOMINGO'],
        ['code' => '03', 'Muncity' => 'TALAVERA'],
        ['code' => '03', 'Muncity' => 'TALUGTUG'],
        ['code' => '03', 'Muncity' => 'ZARAGOZA'],
        ['code' => '03', 'Muncity' => 'ANGELES CITY'],
        ['code' => '03', 'Muncity' => 'APALIT'],
        ['code' => '03', 'Muncity' => 'ARAYAT'],
        ['code' => '03', 'Muncity' => 'BACOLOR'],
        ['code' => '03', 'Muncity' => 'CANDABA'],
        ['code' => '03', 'Muncity' => 'FLORABLANCA'],
        ['code' => '03', 'Muncity' => 'GUAGUA'],
        ['code' => '03', 'Muncity' => 'LUBAO'],
        ['code' => '03', 'Muncity' => 'MABALACAT'],
        ['code' => '03', 'Muncity' => 'MACABEBE'],
        ['code' => '03', 'Muncity' => 'MAGALANG'],
        ['code' => '03', 'Muncity' => 'MASANTOL'],
        ['code' => '03', 'Muncity' => 'MEXICO'],
        ['code' => '03', 'Muncity' => 'MINALIN'],
        ['code' => '03', 'Muncity' => 'PORAC'],
        ['code' => '03', 'Muncity' => 'CITY OF SAN FERNANDO (Capital)'],
        ['code' => '03', 'Muncity' => 'SAN LUIS'],
        ['code' => '03', 'Muncity' => 'SAN SIMON'],
        ['code' => '03', 'Muncity' => 'SANTA ANA'],
        ['code' => '03', 'Muncity' => 'SANTA RITA'],
        ['code' => '03', 'Muncity' => 'SANTO TOMAS'],
        ['code' => '03', 'Muncity' => 'SASMUAN (SEXMOAN)'],
        ['code' => '03', 'Muncity' => 'ANAO'],
        ['code' => '03', 'Muncity' => 'BAMBAN'],
        ['code' => '03', 'Muncity' => 'CAMILING'],
        ['code' => '03', 'Muncity' => 'CAPAS'],
        ['code' => '03', 'Muncity' => 'CONCEPCION'],
        ['code' => '03', 'Muncity' => 'GERONA'],
        ['code' => '03', 'Muncity' => 'LA PAZ'],
        ['code' => '03', 'Muncity' => 'MAYANTOC'],
        ['code' => '03', 'Muncity' => 'MONCADA'],
        ['code' => '03', 'Muncity' => 'PANIQUI'],
        ['code' => '03', 'Muncity' => 'PURA'],
        ['code' => '03', 'Muncity' => 'RAMOS'],
        ['code' => '03', 'Muncity' => 'SAN CLEMENTE'],
        ['code' => '03', 'Muncity' => 'SAN MANUEL'],
        ['code' => '03', 'Muncity' => 'SANTA IGNACIA'],
        ['code' => '03', 'Muncity' => 'CITY OF TARLAC (Capital)'],
        ['code' => '03', 'Muncity' => 'VICTORIA'],
        ['code' => '03', 'Muncity' => 'SAN JOSE'],
        ['code' => '03', 'Muncity' => 'BOTOLAN'],
        ['code' => '03', 'Muncity' => 'CABANGAN'],
        ['code' => '03', 'Muncity' => 'CANDELARIA'],
        ['code' => '03', 'Muncity' => 'CASTILLEJOS'],
        ['code' => '03', 'Muncity' => 'IBA (Capital)'],
        ['code' => '03', 'Muncity' => 'MASINLOC'],
        ['code' => '03', 'Muncity' => 'OLONGAPO CITY'],
        ['code' => '03', 'Muncity' => 'PALAUIG'],
        ['code' => '03', 'Muncity' => 'SAN ANTONIO'],
        ['code' => '03', 'Muncity' => 'SAN FELIPE'],
        ['code' => '03', 'Muncity' => 'SAN MARCELINO'],
        ['code' => '03', 'Muncity' => 'SAN NARCISO'],
        ['code' => '03', 'Muncity' => 'SANTA CRUZ'],
        ['code' => '03', 'Muncity' => 'SUBIC'],
        ['code' => '03', 'Muncity' => 'BALER (Capital)'],
        ['code' => '03', 'Muncity' => 'CASIGURAN'],
        ['code' => '03', 'Muncity' => 'DILASAG'],
        ['code' => '03', 'Muncity' => 'DINALUNGAN'],
        ['code' => '03', 'Muncity' => 'DINGALAN'],
        ['code' => '03', 'Muncity' => 'DIPACULAO'],
        ['code' => '03', 'Muncity' => 'MARIA AURORA'],
        ['code' => '03', 'Muncity' => 'SAN LUIS'],
        ['code' => '04', 'Muncity' => 'AGONCILLO'],
        ['code' => '04', 'Muncity' => 'ALITAGTAG'],
        ['code' => '04', 'Muncity' => 'BALAYAN'],
        ['code' => '04', 'Muncity' => 'BALETE'],
        ['code' => '04', 'Muncity' => 'BATANGAS CITY (Capital)'],
        ['code' => '04', 'Muncity' => 'BAUAN'],
        ['code' => '04', 'Muncity' => 'CALACA'],
        ['code' => '04', 'Muncity' => 'CALATAGAN'],
        ['code' => '04', 'Muncity' => 'CUENCA'],
        ['code' => '04', 'Muncity' => 'IBAAN'],
        ['code' => '04', 'Muncity' => 'LAUREL'],
        ['code' => '04', 'Muncity' => 'LEMERY'],
        ['code' => '04', 'Muncity' => 'LIAN'],
        ['code' => '04', 'Muncity' => 'LIPA CITY'],
        ['code' => '04', 'Muncity' => 'LOBO'],
        ['code' => '04', 'Muncity' => 'MABINI'],
        ['code' => '04', 'Muncity' => 'MALVAR'],
        ['code' => '04', 'Muncity' => 'MATAAS NA KAHOY'],
        ['code' => '04', 'Muncity' => 'NASUGBU'],
        ['code' => '04', 'Muncity' => 'PADRE GARCIA'],
        ['code' => '04', 'Muncity' => 'ROSARIO'],
        ['code' => '04', 'Muncity' => 'SAN JOSE'],
        ['code' => '04', 'Muncity' => 'SAN JUAN'],
        ['code' => '04', 'Muncity' => 'SAN LUIS'],
        ['code' => '04', 'Muncity' => 'SAN NICOLAS'],
        ['code' => '04', 'Muncity' => 'SAN PASCUAL'],
        ['code' => '04', 'Muncity' => 'SANTA TERESITA'],
        ['code' => '04', 'Muncity' => 'SANTO TOMAS'],
        ['code' => '04', 'Muncity' => 'TAAL'],
        ['code' => '04', 'Muncity' => 'TALISAY'],
        ['code' => '04', 'Muncity' => 'CITY OF TANAUAN'],
        ['code' => '04', 'Muncity' => 'TAYSAN'],
        ['code' => '04', 'Muncity' => 'TINGLOY'],
        ['code' => '04', 'Muncity' => 'TUY'],
        ['code' => '04', 'Muncity' => 'ALFONSO'],
        ['code' => '04', 'Muncity' => 'AMADEO'],
        ['code' => '04', 'Muncity' => 'BACOOR'],
        ['code' => '04', 'Muncity' => 'CARMONA'],
        ['code' => '04', 'Muncity' => 'CAVITE CITY'],
        ['code' => '04', 'Muncity' => 'DASMARIÑAS'],
        ['code' => '04', 'Muncity' => 'GENERAL EMILIO AGUINALDO'],
        ['code' => '04', 'Muncity' => 'GENERAL TRIAS'],
        ['code' => '04', 'Muncity' => 'IMUS'],
        ['code' => '04', 'Muncity' => 'INDANG'],
        ['code' => '04', 'Muncity' => 'KAWIT'],
        ['code' => '04', 'Muncity' => 'MAGALLANES'],
        ['code' => '04', 'Muncity' => 'MARAGONDON'],
        ['code' => '04', 'Muncity' => 'MENDEZ (MENDEZ-NUÑEZ)'],
        ['code' => '04', 'Muncity' => 'NAIC'],
        ['code' => '04', 'Muncity' => 'NOVELETA'],
        ['code' => '04', 'Muncity' => 'ROSARIO'],
        ['code' => '04', 'Muncity' => 'SILANG'],
        ['code' => '04', 'Muncity' => 'TAGAYTAY CITY'],
        ['code' => '04', 'Muncity' => 'TANZA'],
        ['code' => '04', 'Muncity' => 'TERNATE'],
        ['code' => '04', 'Muncity' => 'TRECE MARTIRES CITY (Capital)'],
        ['code' => '04', 'Muncity' => 'GEN. MARIANO ALVAREZ'],
        ['code' => '04', 'Muncity' => 'ALAMINOS'],
        ['code' => '04', 'Muncity' => 'BAY'],
        ['code' => '04', 'Muncity' => 'BIÑAN'],
        ['code' => '04', 'Muncity' => 'CABUYAO'],
        ['code' => '04', 'Muncity' => 'CITY OF CALAMBA'],
        ['code' => '04', 'Muncity' => 'CALAUAN'],
        ['code' => '04', 'Muncity' => 'CAVINTI'],
        ['code' => '04', 'Muncity' => 'FAMY'],
        ['code' => '04', 'Muncity' => 'KALAYAAN'],
        ['code' => '04', 'Muncity' => 'LILIW'],
        ['code' => '04', 'Muncity' => 'LOS BAÑOS'],
        ['code' => '04', 'Muncity' => 'LUISIANA'],
        ['code' => '04', 'Muncity' => 'LUMBAN'],
        ['code' => '04', 'Muncity' => 'MABITAC'],
        ['code' => '04', 'Muncity' => 'MAGDALENA'],
        ['code' => '04', 'Muncity' => 'MAJAYJAY'],
        ['code' => '04', 'Muncity' => 'NAGCARLAN'],
        ['code' => '04', 'Muncity' => 'PAETE'],
        ['code' => '04', 'Muncity' => 'PAGSANJAN'],
        ['code' => '04', 'Muncity' => 'PAKIL'],
        ['code' => '04', 'Muncity' => 'PANGIL'],
        ['code' => '04', 'Muncity' => 'PILA'],
        ['code' => '04', 'Muncity' => 'RIZAL'],
        ['code' => '04', 'Muncity' => 'SAN PABLO CITY'],
        ['code' => '04', 'Muncity' => 'SAN PEDRO'],
        ['code' => '04', 'Muncity' => 'SANTA CRUZ (Capital)'],
        ['code' => '04', 'Muncity' => 'SANTA MARIA'],
        ['code' => '04', 'Muncity' => 'SANTA ROSA'],
        ['code' => '04', 'Muncity' => 'SINILOAN'],
        ['code' => '04', 'Muncity' => 'VICTORIA'],
        ['code' => '04', 'Muncity' => 'AGDANGAN'],
        ['code' => '04', 'Muncity' => 'ALABAT'],
        ['code' => '04', 'Muncity' => 'ATIMONAN'],
        ['code' => '04', 'Muncity' => 'BUENAVISTA'],
        ['code' => '04', 'Muncity' => 'BURDEOS'],
        ['code' => '04', 'Muncity' => 'CALAUAG'],
        ['code' => '04', 'Muncity' => 'CANDELARIA'],
        ['code' => '04', 'Muncity' => 'CATANAUAN'],
        ['code' => '04', 'Muncity' => 'DOLORES'],
        ['code' => '04', 'Muncity' => 'GENERAL LUNA'],
        ['code' => '04', 'Muncity' => 'GENERAL NAKAR'],
        ['code' => '04', 'Muncity' => 'GUINAYANGAN'],
        ['code' => '04', 'Muncity' => 'GUMACA'],
        ['code' => '04', 'Muncity' => 'INFANTA'],
        ['code' => '04', 'Muncity' => 'JOMALIG'],
        ['code' => '04', 'Muncity' => 'LOPEZ'],
        ['code' => '04', 'Muncity' => 'LUCBAN'],
        ['code' => '04', 'Muncity' => 'LUCENA CITY (Capital)'],
        ['code' => '04', 'Muncity' => 'MACALELON'],
        ['code' => '04', 'Muncity' => 'MAUBAN'],
        ['code' => '04', 'Muncity' => 'MULANAY'],
        ['code' => '04', 'Muncity' => 'PADRE BURGOS'],
        ['code' => '04', 'Muncity' => 'PAGBILAO'],
        ['code' => '04', 'Muncity' => 'PANUKULAN'],
        ['code' => '04', 'Muncity' => 'PATNANUNGAN'],
        ['code' => '04', 'Muncity' => 'PEREZ'],
        ['code' => '04', 'Muncity' => 'PITOGO'],
        ['code' => '04', 'Muncity' => 'PLAREL'],
        ['code' => '04', 'Muncity' => 'POLILLO'],
        ['code' => '04', 'Muncity' => 'QUEZON'],
        ['code' => '04', 'Muncity' => 'REAL'],
        ['code' => '04', 'Muncity' => 'SAMPALOC'],
        ['code' => '04', 'Muncity' => 'SAN ANDRES'],
        ['code' => '04', 'Muncity' => 'SAN ANTONIO'],
        ['code' => '04', 'Muncity' => 'SAN FRANCISCO (AURORA)'],
        ['code' => '04', 'Muncity' => 'SAN NARCISO'],
        ['code' => '04', 'Muncity' => 'SARIAYA'],
        ['code' => '04', 'Muncity' => 'TAGKAWAYAN'],
        ['code' => '04', 'Muncity' => 'TAYABAS'],
        ['code' => '04', 'Muncity' => 'TIAONG'],
        ['code' => '04', 'Muncity' => 'UNISAN'],
        ['code' => '04', 'Muncity' => 'ANGONO'],
        ['code' => '04', 'Muncity' => 'CITY OF ANTIPOLO'],
        ['code' => '04', 'Muncity' => 'BARAS'],
        ['code' => '04', 'Muncity' => 'BINANGONAN'],
        ['code' => '04', 'Muncity' => 'CAINTA'],
        ['code' => '04', 'Muncity' => 'CARDONA'],
        ['code' => '04', 'Muncity' => 'JALA-JALA'],
        ['code' => '04', 'Muncity' => 'RODRIGUEZ (MONTALBAN)'],
        ['code' => '04', 'Muncity' => 'MORONG'],
        ['code' => '04', 'Muncity' => 'PILILLA'],
        ['code' => '04', 'Muncity' => 'SAN MATEO'],
        ['code' => '04', 'Muncity' => 'TANAY'],
        ['code' => '04', 'Muncity' => 'TAYTAY'],
        ['code' => '04', 'Muncity' => 'TERESA'],
        ['code' => '05', 'Muncity' => 'BACACAY'],
        ['code' => '05', 'Muncity' => 'CAMALIG'],
        ['code' => '05', 'Muncity' => 'DARAGA (LOCSIN)'],
        ['code' => '05', 'Muncity' => 'GUINOBATAN'],
        ['code' => '05', 'Muncity' => 'JOVELLAR'],
        ['code' => '05', 'Muncity' => 'LEGAZPI CITY (Capital)'],
        ['code' => '05', 'Muncity' => 'LIBON'],
        ['code' => '05', 'Muncity' => 'CITY OF LIGAO'],
        ['code' => '05', 'Muncity' => 'MALILIPOT'],
        ['code' => '05', 'Muncity' => 'MALINAO'],
        ['code' => '05', 'Muncity' => 'MANITO'],
        ['code' => '05', 'Muncity' => 'OAS'],
        ['code' => '05', 'Muncity' => 'PIO DURAN'],
        ['code' => '05', 'Muncity' => 'POLANGUI'],
        ['code' => '05', 'Muncity' => 'RAPU-RAPU'],
        ['code' => '05', 'Muncity' => 'SANTO DOMINGO (LIBOG)'],
        ['code' => '05', 'Muncity' => 'CITY OF TABACO'],
        ['code' => '05', 'Muncity' => 'TIWI'],
        ['code' => '05', 'Muncity' => 'BASUD'],
        ['code' => '05', 'Muncity' => 'CAPALONGA'],
        ['code' => '05', 'Muncity' => 'DAET (Capital)'],
        ['code' => '05', 'Muncity' => 'SAN LORENZO RUIZ (IMELDA)'],
        ['code' => '05', 'Muncity' => 'JOSE PANGANIBAN'],
        ['code' => '05', 'Muncity' => 'LABO'],
        ['code' => '05', 'Muncity' => 'MERCEDES'],
        ['code' => '05', 'Muncity' => 'PARACALE'],
        ['code' => '05', 'Muncity' => 'SAN VICENTE'],
        ['code' => '05', 'Muncity' => 'SANTA ELENA'],
        ['code' => '05', 'Muncity' => 'TALISAY'],
        ['code' => '05', 'Muncity' => 'VINZONS'],
        ['code' => '05', 'Muncity' => 'BAAO'],
        ['code' => '05', 'Muncity' => 'BALATAN'],
        ['code' => '05', 'Muncity' => 'BATO'],
        ['code' => '05', 'Muncity' => 'BOMBON'],
        ['code' => '05', 'Muncity' => 'BUHI'],
        ['code' => '05', 'Muncity' => 'BULA'],
        ['code' => '05', 'Muncity' => 'CABUSAO'],
        ['code' => '05', 'Muncity' => 'CALABANGA'],
        ['code' => '05', 'Muncity' => 'CAMALIGAN'],
        ['code' => '05', 'Muncity' => 'CANAMAN'],
        ['code' => '05', 'Muncity' => 'CARAMOAN'],
        ['code' => '05', 'Muncity' => 'DEL GALLEGO'],
        ['code' => '05', 'Muncity' => 'GAINZA'],
        ['code' => '05', 'Muncity' => 'GARCHITORENA'],
        ['code' => '05', 'Muncity' => 'GOA'],
        ['code' => '05', 'Muncity' => 'IRIGA CITY'],
        ['code' => '05', 'Muncity' => 'LAGONOY'],
        ['code' => '05', 'Muncity' => 'LIBMANAN'],
        ['code' => '05', 'Muncity' => 'LUPI'],
        ['code' => '05', 'Muncity' => 'MAGARAO'],
        ['code' => '05', 'Muncity' => 'MILAOR'],
        ['code' => '05', 'Muncity' => 'MINALABAC'],
        ['code' => '05', 'Muncity' => 'NABUA'],
        ['code' => '05', 'Muncity' => 'NAGA CITY'],
        ['code' => '05', 'Muncity' => 'OCAMPO'],
        ['code' => '05', 'Muncity' => 'PAMPLONA'],
        ['code' => '05', 'Muncity' => 'PASACAO'],
        ['code' => '05', 'Muncity' => 'PILI (Capital)'],
        ['code' => '05', 'Muncity' => 'PRESENTACION (PARUBCAN)'],
        ['code' => '05', 'Muncity' => 'RAGAY'],
        ['code' => '05', 'Muncity' => 'SAGÑAY'],
        ['code' => '05', 'Muncity' => 'SAN FERNANDO'],
        ['code' => '05', 'Muncity' => 'SAN JOSE'],
        ['code' => '05', 'Muncity' => 'SIPOCOT'],
        ['code' => '05', 'Muncity' => 'SIRUMA'],
        ['code' => '05', 'Muncity' => 'TIGAON'],
        ['code' => '05', 'Muncity' => 'TINAMBAC'],
        ['code' => '05', 'Muncity' => 'BAGAMANOC'],
        ['code' => '05', 'Muncity' => 'BARAS'],
        ['code' => '05', 'Muncity' => 'BATO'],
        ['code' => '05', 'Muncity' => 'CARAMORAN'],
        ['code' => '05', 'Muncity' => 'GIGMOTO'],
        ['code' => '05', 'Muncity' => 'PANDAN'],
        ['code' => '05', 'Muncity' => 'PANGANIBAN (PAYO)'],
        ['code' => '05', 'Muncity' => 'SAN ANDRES (CALOLBON)'],
        ['code' => '05', 'Muncity' => 'SAN MIGUEL'],
        ['code' => '05', 'Muncity' => 'VIGA'],
        ['code' => '05', 'Muncity' => 'VIRAC (Capital)'],
        ['code' => '05', 'Muncity' => 'AROROY'],
        ['code' => '05', 'Muncity' => 'BALENO'],
        ['code' => '05', 'Muncity' => 'BALUD'],
        ['code' => '05', 'Muncity' => 'BATUAN'],
        ['code' => '05', 'Muncity' => 'CATAINGAN'],
        ['code' => '05', 'Muncity' => 'CAWAYAN'],
        ['code' => '05', 'Muncity' => 'CLAVERIA'],
        ['code' => '05', 'Muncity' => 'DIMASALANG'],
        ['code' => '05', 'Muncity' => 'ESPERANZA'],
        ['code' => '05', 'Muncity' => 'MANDAON'],
        ['code' => '05', 'Muncity' => 'CITY OF MASBATE (Capital)'],
        ['code' => '05', 'Muncity' => 'MILAGROS'],
        ['code' => '05', 'Muncity' => 'MOBO'],
        ['code' => '05', 'Muncity' => 'MONREAL'],
        ['code' => '05', 'Muncity' => 'PALANAS'],
        ['code' => '05', 'Muncity' => 'PIO V. CORPUZ (LIMBUHAN)'],
        ['code' => '05', 'Muncity' => 'PLACER'],
        ['code' => '05', 'Muncity' => 'SAN FERNANDO'],
        ['code' => '05', 'Muncity' => 'SAN JACINTO'],
        ['code' => '05', 'Muncity' => 'SAN PASCUAL'],
        ['code' => '05', 'Muncity' => 'USON'],
        ['code' => '05', 'Muncity' => 'BARCELONA'],
        ['code' => '05', 'Muncity' => 'BULAN'],
        ['code' => '05', 'Muncity' => 'BULUSAN'],
        ['code' => '05', 'Muncity' => 'CASIGURAN'],
        ['code' => '05', 'Muncity' => 'CASTILLA'],
        ['code' => '05', 'Muncity' => 'DONSOL'],
        ['code' => '05', 'Muncity' => 'GUBAT'],
        ['code' => '05', 'Muncity' => 'IROSIN'],
        ['code' => '05', 'Muncity' => 'JUBAN'],
        ['code' => '05', 'Muncity' => 'MAGALLANES (34 BRGYS)'],
        ['code' => '05', 'Muncity' => 'MATNOG'],
        ['code' => '05', 'Muncity' => 'PILAR'],
        ['code' => '05', 'Muncity' => 'PRIETO DIAZ'],
        ['code' => '05', 'Muncity' => 'SANTA MAGDALENA'],
        ['code' => '05', 'Muncity' => 'CITY OF SORSOGON (Capital)'],
        ['code' => '06', 'Muncity' => 'ALTAVAS'],
        ['code' => '06', 'Muncity' => 'BALETE'],
        ['code' => '06', 'Muncity' => 'BANGA'],
        ['code' => '06', 'Muncity' => 'BATAN'],
        ['code' => '06', 'Muncity' => 'BURUANGA'],
        ['code' => '06', 'Muncity' => 'IBAJAY'],
        ['code' => '06', 'Muncity' => 'KALIBO (Capital)'],
        ['code' => '06', 'Muncity' => 'LEZO'],
        ['code' => '06', 'Muncity' => 'LIBACAO'],
        ['code' => '06', 'Muncity' => 'MADALAG'],
        ['code' => '06', 'Muncity' => 'MAKATO'],
        ['code' => '06', 'Muncity' => 'MALAY'],
        ['code' => '06', 'Muncity' => 'MALINAO'],
        ['code' => '06', 'Muncity' => 'NABAS'],
        ['code' => '06', 'Muncity' => 'NEW WASHINGTON'],
        ['code' => '06', 'Muncity' => 'NUMANCIA'],
        ['code' => '06', 'Muncity' => 'TANGALAN'],
        ['code' => '06', 'Muncity' => 'ANINI-Y'],
        ['code' => '06', 'Muncity' => 'BARBAZA'],
        ['code' => '06', 'Muncity' => 'BELISON'],
        ['code' => '06', 'Muncity' => 'BUGASONG'],
        ['code' => '06', 'Muncity' => 'CALUYA'],
        ['code' => '06', 'Muncity' => 'CULASI'],
        ['code' => '06', 'Muncity' => 'TOBIAS FORNIER (DAO)'],
        ['code' => '06', 'Muncity' => 'HAMTIC'],
        ['code' => '06', 'Muncity' => 'LAUA-AN'],
        ['code' => '06', 'Muncity' => 'LIBERTAD'],
        ['code' => '06', 'Muncity' => 'PANDAN'],
        ['code' => '06', 'Muncity' => 'PATNONGON'],
        ['code' => '06', 'Muncity' => 'SAN JOSE (Capital)'],
        ['code' => '06', 'Muncity' => 'SAN REMIGIO'],
        ['code' => '06', 'Muncity' => 'SEBASTE'],
        ['code' => '06', 'Muncity' => 'SIBALOM'],
        ['code' => '06', 'Muncity' => 'TIBIAO'],
        ['code' => '06', 'Muncity' => 'VALDERRAMA'],
        ['code' => '06', 'Muncity' => 'CUARTERO'],
        ['code' => '06', 'Muncity' => 'DAO'],
        ['code' => '06', 'Muncity' => 'DUMALAG'],
        ['code' => '06', 'Muncity' => 'DUMARAO'],
        ['code' => '06', 'Muncity' => 'IVISAN'],
        ['code' => '06', 'Muncity' => 'JAMINDAN'],
        ['code' => '06', 'Muncity' => 'MA-AYON'],
        ['code' => '06', 'Muncity' => 'MAMBUSAO'],
        ['code' => '06', 'Muncity' => 'PANAY'],
        ['code' => '06', 'Muncity' => 'PANITAN'],
        ['code' => '06', 'Muncity' => 'PILAR'],
        ['code' => '06', 'Muncity' => 'PONTEVEDRA'],
        ['code' => '06', 'Muncity' => 'PRESENT ROXAS'],
        ['code' => '06', 'Muncity' => 'ROXAS CITY (Capital)'],
        ['code' => '06', 'Muncity' => 'SAPI-AN'],
        ['code' => '06', 'Muncity' => 'SIGMA'],
        ['code' => '06', 'Muncity' => 'TAPAZ'],
        ['code' => '06', 'Muncity' => 'AJUY'],
        ['code' => '06', 'Muncity' => 'ALIMODIAN'],
        ['code' => '06', 'Muncity' => 'ANILAO'],
        ['code' => '06', 'Muncity' => 'BADIANGAN'],
        ['code' => '06', 'Muncity' => 'BALASAN'],
        ['code' => '06', 'Muncity' => 'BANATE'],
        ['code' => '06', 'Muncity' => 'BAROTAC NUEVO'],
        ['code' => '06', 'Muncity' => 'BAROTAC VIEJO'],
        ['code' => '06', 'Muncity' => 'BATAD'],
        ['code' => '06', 'Muncity' => 'BINGAWAN'],
        ['code' => '06', 'Muncity' => 'CABATUAN'],
        ['code' => '06', 'Muncity' => 'CALINOG'],
        ['code' => '06', 'Muncity' => 'CARLES'],
        ['code' => '06', 'Muncity' => 'CONCEPCION'],
        ['code' => '06', 'Muncity' => 'DINGLE'],
        ['code' => '06', 'Muncity' => 'DUEÑAS'],
        ['code' => '06', 'Muncity' => 'DUMANGAS'],
        ['code' => '06', 'Muncity' => 'ESTANCIA'],
        ['code' => '06', 'Muncity' => 'GUIMBAL'],
        ['code' => '06', 'Muncity' => 'IGBARAS'],
        ['code' => '06', 'Muncity' => 'ILOILO CITY (Capital)'],
        ['code' => '06', 'Muncity' => 'JANIUAY'],
        ['code' => '06', 'Muncity' => 'LAMBUNAO'],
        ['code' => '06', 'Muncity' => 'LEGANES'],
        ['code' => '06', 'Muncity' => 'LEMERY'],
        ['code' => '06', 'Muncity' => 'LEON'],
        ['code' => '06', 'Muncity' => 'MAASIN'],
        ['code' => '06', 'Muncity' => 'MIAGAO'],
        ['code' => '06', 'Muncity' => 'MINA'],
        ['code' => '06', 'Muncity' => 'NEW LUCENA'],
        ['code' => '06', 'Muncity' => 'OTON'],
        ['code' => '06', 'Muncity' => 'CITY OF PASSI'],
        ['code' => '06', 'Muncity' => 'PAVIA'],
        ['code' => '06', 'Muncity' => 'POTOTAN'],
        ['code' => '06', 'Muncity' => 'SAN DIONISIO'],
        ['code' => '06', 'Muncity' => 'SAN ENRIQUE'],
        ['code' => '06', 'Muncity' => 'SAN JOAQUIN'],
        ['code' => '06', 'Muncity' => 'SAN MIGUEL'],
        ['code' => '06', 'Muncity' => 'SAN RAFAEL'],
        ['code' => '06', 'Muncity' => 'SANTA BARBARA'],
        ['code' => '06', 'Muncity' => 'SARA'],
        ['code' => '06', 'Muncity' => 'TIGBAUAN'],
        ['code' => '06', 'Muncity' => 'TUBUNGAN'],
        ['code' => '06', 'Muncity' => 'ZARRAGA'],        
        ['code' => '06', 'Muncity' => 'BUENAVISTA'],
        ['code' => '06', 'Muncity' => 'JORDAN (Capital)'],
        ['code' => '06', 'Muncity' => 'NUEVA VALENCIA'],
        ['code' => '06', 'Muncity' => 'SAN LORENZO'],
        ['code' => '06', 'Muncity' => 'SIBUNAG'],
        ['code' => '07', 'Muncity' => 'ALBURQUERQUE'],
        ['code' => '07', 'Muncity' => 'ALICIA'],
        ['code' => '07', 'Muncity' => 'ANDA'],
        ['code' => '07', 'Muncity' => 'ANTEQUERA'],
        ['code' => '07', 'Muncity' => 'BACLAYON'],
        ['code' => '07', 'Muncity' => 'BALILIHAN'],
        ['code' => '07', 'Muncity' => 'BATUAN'],
        ['code' => '07', 'Muncity' => 'BILAR'],
        ['code' => '07', 'Muncity' => 'BUENAVISTA'],
        ['code' => '07', 'Muncity' => 'CALAPE'],
        ['code' => '07', 'Muncity' => 'CANDIJAY'],
        ['code' => '07', 'Muncity' => 'CARMEN'],
        ['code' => '07', 'Muncity' => 'CATIGBIAN'],
        ['code' => '07', 'Muncity' => 'CLARIN'],
        ['code' => '07', 'Muncity' => 'CORELLA'],
        ['code' => '07', 'Muncity' => 'CORTES'],
        ['code' => '07', 'Muncity' => 'DAGOHOY'],
        ['code' => '07', 'Muncity' => 'DANAO'],
        ['code' => '07', 'Muncity' => 'DAUIS'],
        ['code' => '07', 'Muncity' => 'DIMIAO'],
        ['code' => '07', 'Muncity' => 'DUERO'],
        ['code' => '07', 'Muncity' => 'GARCIA HERNANDEZ'],
        ['code' => '07', 'Muncity' => 'GUINDULMAN'],
        ['code' => '07', 'Muncity' => 'INABANGA'],
        ['code' => '07', 'Muncity' => 'JAGNA'],
        ['code' => '07', 'Muncity' => 'JETAFE'],
        ['code' => '07', 'Muncity' => 'LILA'],
        ['code' => '07', 'Muncity' => 'LOAY'],
        ['code' => '07', 'Muncity' => 'LOBOC'],
        ['code' => '07', 'Muncity' => 'LOON'],
        ['code' => '07', 'Muncity' => 'MABINI'],
        ['code' => '07', 'Muncity' => 'MARIBOJOC'],
        ['code' => '07', 'Muncity' => 'PANGLAO'],
        ['code' => '07', 'Muncity' => 'PILAR'],
        ['code' => '07', 'Muncity' => 'PRES. CARLOS P. GARCIA (PITOGO)'],
        ['code' => '07', 'Muncity' => 'SAGBAYAN (BORJA)'],
        ['code' => '07', 'Muncity' => 'SAN ISRO'],
        ['code' => '07', 'Muncity' => 'SAN MIGUEL'],
        ['code' => '07', 'Muncity' => 'SEVILLA'],
        ['code' => '07', 'Muncity' => 'SIERRA BULLONES'],
        ['code' => '07', 'Muncity' => 'SIKATUNA'],
        ['code' => '07', 'Muncity' => 'TAGBILARAN CITY (Capital)'],
        ['code' => '07', 'Muncity' => 'TALIBON'],
        ['code' => '07', 'Muncity' => 'TRINAD'],
        ['code' => '07', 'Muncity' => 'TUBIGON'],
        ['code' => '07', 'Muncity' => 'UBAY'],
        ['code' => '07', 'Muncity' => 'VALENCIA'],
        ['code' => '07', 'Muncity' => 'BIEN UNO'],
        ['code' => '07', 'Muncity' => 'ALCANTARA'],
        ['code' => '07', 'Muncity' => 'ALCOY'],
        ['code' => '07', 'Muncity' => 'ALEGRIA'],
        ['code' => '07', 'Muncity' => 'ALOGUINSAN'],
        ['code' => '07', 'Muncity' => 'ARGAO'],
        ['code' => '07', 'Muncity' => 'ASTURIAS'],
        ['code' => '07', 'Muncity' => 'BADIAN'],
        ['code' => '07', 'Muncity' => 'BALAMBAN'],
        ['code' => '07', 'Muncity' => 'BANTAYAN'],
        ['code' => '07', 'Muncity' => 'BARILI'],
        ['code' => '07', 'Muncity' => 'BOGO'],
        ['code' => '07', 'Muncity' => 'BOLJOON'],
        ['code' => '07', 'Muncity' => 'BORBON'],
        ['code' => '07', 'Muncity' => 'CARCAR'],
        ['code' => '07', 'Muncity' => 'CARMEN'],
        ['code' => '07', 'Muncity' => 'CATMON'],
        ['code' => '07', 'Muncity' => 'CEBU CITY (Capital)'],
        ['code' => '07', 'Muncity' => 'COMPOSTELA'],
        ['code' => '07', 'Muncity' => 'CONSOLACION'],
        ['code' => '07', 'Muncity' => 'CORDOBA'],
        ['code' => '07', 'Muncity' => 'DAANBANTAYAN'],
        ['code' => '07', 'Muncity' => 'DALAGUETE'],
        ['code' => '07', 'Muncity' => 'DANAO CITY'],
        ['code' => '07', 'Muncity' => 'DUMANJUG'],
        ['code' => '07', 'Muncity' => 'GINATILAN'],
        ['code' => '07', 'Muncity' => 'LAPU-LAPU CITY (OPON)'],
        ['code' => '07', 'Muncity' => 'LILOAN'],
        ['code' => '07', 'Muncity' => 'MADREJOS'],
        ['code' => '07', 'Muncity' => 'MALABUYOC'],
        ['code' => '07', 'Muncity' => 'MANDAUE CITY'],
        ['code' => '07', 'Muncity' => 'MEDELLIN'],
        ['code' => '07', 'Muncity' => 'MINGLANILLA'],
        ['code' => '07', 'Muncity' => 'MOALBOAL'],
        ['code' => '07', 'Muncity' => 'NAGA'],
        ['code' => '07', 'Muncity' => 'OSLOB'],
        ['code' => '07', 'Muncity' => 'PILAR'],
        ['code' => '07', 'Muncity' => 'PINAMUNGAHAN'],
        ['code' => '07', 'Muncity' => 'PORO'],
        ['code' => '07', 'Muncity' => 'RONDA'],
        ['code' => '07', 'Muncity' => 'SAMBOAN'],
        ['code' => '07', 'Muncity' => 'SAN FERNANDO'],
        ['code' => '07', 'Muncity' => 'SAN FRANCISCO'],
        ['code' => '07', 'Muncity' => 'SAN REMIGIO'],
        ['code' => '07', 'Muncity' => 'SANTA FE'],
        ['code' => '07', 'Muncity' => 'SANTANDER'],
        ['code' => '07', 'Muncity' => 'SIBONGA'],
        ['code' => '07', 'Muncity' => 'SOGOD'],
        ['code' => '07', 'Muncity' => 'TABOGON'],
        ['code' => '07', 'Muncity' => 'TABUELAN'],
        ['code' => '07', 'Muncity' => 'CITY OF TALISAY'],
        ['code' => '07', 'Muncity' => 'TOLEDO CITY'],
        ['code' => '07', 'Muncity' => 'TUBURAN'],
        ['code' => '07', 'Muncity' => 'TUDELA'],        
        ['code' => '07', 'Muncity' => 'ENRIQUE VILLANUEVA'],
        ['code' => '07', 'Muncity' => 'LARENA'],
        ['code' => '07', 'Muncity' => 'LAZI'],
        ['code' => '07', 'Muncity' => 'MARIA'],
        ['code' => '07', 'Muncity' => 'SAN JUAN'],
        ['code' => '07', 'Muncity' => 'SIQUIJOR (Capital)'],
        ['code' => '08', 'Muncity' => 'ARTECHE'],
        ['code' => '08', 'Muncity' => 'BALANGIGA'],
        ['code' => '08', 'Muncity' => 'BALANGKAYAN'],
        ['code' => '08', 'Muncity' => 'BORONGAN (Capital)'],
        ['code' => '08', 'Muncity' => 'CAN-AV'],
        ['code' => '08', 'Muncity' => 'DOLORES'],
        ['code' => '08', 'Muncity' => 'GENERAL MACARTHUR'],
        ['code' => '08', 'Muncity' => 'GIPORLOS'],
        ['code' => '08', 'Muncity' => 'GUIUAN'],
        ['code' => '08', 'Muncity' => 'HERNANI'],
        ['code' => '08', 'Muncity' => 'JIPAPAD'],
        ['code' => '08', 'Muncity' => 'LAWAAN'],
        ['code' => '08', 'Muncity' => 'LLORENTE'],
        ['code' => '08', 'Muncity' => 'MASLOG'],
        ['code' => '08', 'Muncity' => 'MAYDOLONG'],
        ['code' => '08', 'Muncity' => 'MERCEDES'],
        ['code' => '08', 'Muncity' => 'ORAS'],
        ['code' => '08', 'Muncity' => 'QUINAPONDAN'],
        ['code' => '08', 'Muncity' => 'SALCEDO'],
        ['code' => '08', 'Muncity' => 'SAN JULIAN'],
        ['code' => '08', 'Muncity' => 'SAN POLICARPO'],
        ['code' => '08', 'Muncity' => 'SULAT'],
        ['code' => '08', 'Muncity' => 'TAFT'],
        ['code' => '08', 'Muncity' => 'ABUYOG'],
        ['code' => '08', 'Muncity' => 'ALANGALANG'],
        ['code' => '08', 'Muncity' => 'ALBUERA'],
        ['code' => '08', 'Muncity' => 'BABATNGON'],
        ['code' => '08', 'Muncity' => 'BARUGO'],
        ['code' => '08', 'Muncity' => 'BATO'],
        ['code' => '08', 'Muncity' => 'BAYBAY'],
        ['code' => '08', 'Muncity' => 'BURAUEN'],
        ['code' => '08', 'Muncity' => 'CALUBIAN'],
        ['code' => '08', 'Muncity' => 'CAPOOCAN'],
        ['code' => '08', 'Muncity' => 'CARIGARA'],
        ['code' => '08', 'Muncity' => 'DAGAMI'],
        ['code' => '08', 'Muncity' => 'DULAG'],
        ['code' => '08', 'Muncity' => 'HILONGOS'],
        ['code' => '08', 'Muncity' => 'HINDANG'],
        ['code' => '08', 'Muncity' => 'INOPACAN'],
        ['code' => '08', 'Muncity' => 'ISABEL'],
        ['code' => '08', 'Muncity' => 'JARO'],
        ['code' => '08', 'Muncity' => 'JAVIER (BUGHO)'],
        ['code' => '08', 'Muncity' => 'JULITA'],
        ['code' => '08', 'Muncity' => 'KANANGA'],
        ['code' => '08', 'Muncity' => 'LAPAZ'],
        ['code' => '08', 'Muncity' => 'LEYTE'],
        ['code' => '08', 'Muncity' => 'MACARTHUR'],
        ['code' => '08', 'Muncity' => 'MAHAPLAG'],
        ['code' => '08', 'Muncity' => 'MATAG-OB'],
        ['code' => '08', 'Muncity' => 'MATALOM'],
        ['code' => '08', 'Muncity' => 'MAYORGA'],
        ['code' => '08', 'Muncity' => 'MERA'],
        ['code' => '08', 'Muncity' => 'ORMOC CITY'],
        ['code' => '08', 'Muncity' => 'PALO'],
        ['code' => '08', 'Muncity' => 'PALOMPON'],
        ['code' => '08', 'Muncity' => 'PASTRANA'],
        ['code' => '08', 'Muncity' => 'SAN ISRO'],
        ['code' => '08', 'Muncity' => 'SAN MIGUEL'],
        ['code' => '08', 'Muncity' => 'SANTA FE'],
        ['code' => '08', 'Muncity' => 'TABANGO'],
        ['code' => '08', 'Muncity' => 'TABONTABON'],
        ['code' => '08', 'Muncity' => 'TACLOBAN CITY (Capital)'],
        ['code' => '08', 'Muncity' => 'TANAUAN'],
        ['code' => '08', 'Muncity' => 'TOLOSA'],
        ['code' => '08', 'Muncity' => 'TUNGA'],
        ['code' => '08', 'Muncity' => 'VILLABA'],
        ['code' => '08', 'Muncity' => 'ALLEN'],
        ['code' => '08', 'Muncity' => 'BIRI'],
        ['code' => '08', 'Muncity' => 'BOBON'],
        ['code' => '08', 'Muncity' => 'CAPUL'],
        ['code' => '08', 'Muncity' => 'CATARMAN (Capital)'],
        ['code' => '08', 'Muncity' => 'CATUBIG'],
        ['code' => '08', 'Muncity' => 'GAMAY'],
        ['code' => '08', 'Muncity' => 'LAOANG'],
        ['code' => '08', 'Muncity' => 'LAPINIG'],
        ['code' => '08', 'Muncity' => 'LAS NAVAS'],
        ['code' => '08', 'Muncity' => 'LAVEZARES'],
        ['code' => '08', 'Muncity' => 'MAPANAS'],
        ['code' => '08', 'Muncity' => 'MONDRAGON'],
        ['code' => '08', 'Muncity' => 'PALAPAG'],
        ['code' => '08', 'Muncity' => 'PAMBUJAN'],
        ['code' => '08', 'Muncity' => 'ROSARIO'],
        ['code' => '08', 'Muncity' => 'SAN ANTONIO'],
        ['code' => '08', 'Muncity' => 'SAN ISRO'],
        ['code' => '08', 'Muncity' => 'SAN JOSE'],
        ['code' => '08', 'Muncity' => 'SAN ROQUE'],
        ['code' => '08', 'Muncity' => 'SAN VICENTE'],
        ['code' => '08', 'Muncity' => 'SILVINO LOBOS'],
        ['code' => '08', 'Muncity' => 'VICTORIA'],
        ['code' => '08', 'Muncity' => 'LOPE DE VEGA'],
        ['code' => '08', 'Muncity' => 'ALMAGRO'],
        ['code' => '08', 'Muncity' => 'BASEY'],
        ['code' => '08', 'Muncity' => 'CALBAYOG CITY'],
        ['code' => '08', 'Muncity' => 'CALBIGA'],
        ['code' => '08', 'Muncity' => 'CATBALOGAN (Capital)'],
        ['code' => '08', 'Muncity' => 'DARAM'],
        ['code' => '08', 'Muncity' => 'GANDARA'],
        ['code' => '08', 'Muncity' => 'HINABANGAN'],
        ['code' => '08', 'Muncity' => 'JIABONG'],
        ['code' => '08', 'Muncity' => 'MARABUT'],
        ['code' => '08', 'Muncity' => 'MATUGUINAO'],
        ['code' => '08', 'Muncity' => 'MOTIONG'],
        ['code' => '08', 'Muncity' => 'PINABACDAO'],
        ['code' => '08', 'Muncity' => 'SAN JOSE DE BUAN'],
        ['code' => '08', 'Muncity' => 'SAN SEBASTIAN'],
        ['code' => '08', 'Muncity' => 'SANTA MARGARITA'],
        ['code' => '08', 'Muncity' => 'SANTA RITA'],
        ['code' => '08', 'Muncity' => 'SANTO NIÑO'],
        ['code' => '08', 'Muncity' => 'TALALORA'],
        ['code' => '08', 'Muncity' => 'TARANGNAN'],
        ['code' => '08', 'Muncity' => 'VILLAREAL'],
        ['code' => '08', 'Muncity' => 'PARANAS (WRIGHT)'],
        ['code' => '08', 'Muncity' => 'ZUMARRAGA'],
        ['code' => '08', 'Muncity' => 'TAGAPUL-AN'],
        ['code' => '08', 'Muncity' => 'SAN JORGE'],
        ['code' => '08', 'Muncity' => 'PAGSANGHAN'],
        ['code' => '08', 'Muncity' => 'ANAHAWAN'],
        ['code' => '08', 'Muncity' => 'BONTOC'],
        ['code' => '08', 'Muncity' => 'HINUNANGAN'],
        ['code' => '08', 'Muncity' => 'HINUNDAYAN'],
        ['code' => '08', 'Muncity' => 'LIBAGON'],
        ['code' => '08', 'Muncity' => 'LILOAN'],
        ['code' => '08', 'Muncity' => 'CITY OF MAASIN (Capital)'],
        ['code' => '08', 'Muncity' => 'MACROHON'],
        ['code' => '08', 'Muncity' => 'MALITBOG'],
        ['code' => '08', 'Muncity' => 'PADRE BURGOS'],
        ['code' => '08', 'Muncity' => 'PINTUYAN'],
        ['code' => '08', 'Muncity' => 'SAINT BERNARD'],
        ['code' => '08', 'Muncity' => 'SAN FRANCISCO'],
        ['code' => '08', 'Muncity' => 'SAN JUAN (CABALIAN)'],
        ['code' => '08', 'Muncity' => 'SAN RICARDO'],
        ['code' => '08', 'Muncity' => 'SILAGO'],
        ['code' => '08', 'Muncity' => 'SOGOD'],
        ['code' => '08', 'Muncity' => 'TOMAS OPPUS'],
        ['code' => '08', 'Muncity' => 'LIMASAWA'],
        ['code' => '08', 'Muncity' => 'ALMERIA'],
        ['code' => '08', 'Muncity' => 'BILIRAN'],
        ['code' => '08', 'Muncity' => 'CABUCGAYAN'],
        ['code' => '08', 'Muncity' => 'CAIBIRAN'],
        ['code' => '08', 'Muncity' => 'CULABA'],
        ['code' => '08', 'Muncity' => 'KAWAYAN'],
        ['code' => '08', 'Muncity' => 'MARIPIPI'],
        ['code' => '08', 'Muncity' => 'NAVAL (Capital)'],
        ['code' => '09', 'Muncity' => 'DAPITAN CITY'],
        ['code' => '09', 'Muncity' => 'DIPOLOG CITY (Capital)'],
        ['code' => '09', 'Muncity' => 'KATIPUNAN'],
        ['code' => '09', 'Muncity' => 'LA LIBERTAD'],
        ['code' => '09', 'Muncity' => 'LABASON'],
        ['code' => '09', 'Muncity' => 'LILOY'],
        ['code' => '09', 'Muncity' => 'MANUKAN'],
        ['code' => '09', 'Muncity' => 'MUTIA'],
        ['code' => '09', 'Muncity' => 'PIÑAN (NEW PIÑAN)'],
        ['code' => '09', 'Muncity' => 'POLANCO'],
        ['code' => '09', 'Muncity' => 'PRES. MANUEL A. ROXAS'],
        ['code' => '09', 'Muncity' => 'RIZAL'],
        ['code' => '09', 'Muncity' => 'SALUG'],
        ['code' => '09', 'Muncity' => 'SERGIO OSMEÑA SR.'],
        ['code' => '09', 'Muncity' => 'SIAYAN'],
        ['code' => '09', 'Muncity' => 'SIBUCO'],
        ['code' => '09', 'Muncity' => 'SIBUTAD'],
        ['code' => '09', 'Muncity' => 'SINDANGAN'],
        ['code' => '09', 'Muncity' => 'SIOCON'],
        ['code' => '09', 'Muncity' => 'SIRAWAI'],
        ['code' => '09', 'Muncity' => 'TAMPILISAN'],
        ['code' => '09', 'Muncity' => 'JOSE DALMAN (PONOT)'],
        ['code' => '09', 'Muncity' => 'GUTALAC'],
        ['code' => '09', 'Muncity' => 'BALIGUIAN'],
        ['code' => '09', 'Muncity' => 'GODOD'],
        ['code' => '09', 'Muncity' => 'BACUNGAN (LEON T. POSTIGO)'],
        ['code' => '09', 'Muncity' => 'KALAWIT'],
        ['code' => '09', 'Muncity' => 'AURORA'],
        ['code' => '09', 'Muncity' => 'BAYOG'],
        ['code' => '09', 'Muncity' => 'DIMATALING'],
        ['code' => '09', 'Muncity' => 'DINAS'],
        ['code' => '09', 'Muncity' => 'DUMALINAO'],
        ['code' => '09', 'Muncity' => 'DUMINGAG'],
        ['code' => '09', 'Muncity' => 'KUMALARANG'],
        ['code' => '09', 'Muncity' => 'LABANGAN'],
        ['code' => '09', 'Muncity' => 'LAPUYAN'],
        ['code' => '09', 'Muncity' => 'MAHAYAG'],
        ['code' => '09', 'Muncity' => 'MARGOSATUBIG'],
        ['code' => '09', 'Muncity' => 'MSALIP'],
        ['code' => '09', 'Muncity' => 'MOLAVE'],
        ['code' => '09', 'Muncity' => 'PAGADIAN CITY (Capital)'],
        ['code' => '09', 'Muncity' => 'RAMON MAGSAYSAY (LIARGO)'],
        ['code' => '09', 'Muncity' => 'SAN MIGUEL'],
        ['code' => '09', 'Muncity' => 'SAN PABLO'],
        ['code' => '09', 'Muncity' => 'TABINA'],
        ['code' => '09', 'Muncity' => 'TAMBULIG'],
        ['code' => '09', 'Muncity' => 'TUKURAN'],
        ['code' => '09', 'Muncity' => 'ZAMBOANGA CITY'],
        ['code' => '09', 'Muncity' => 'LAKEWOOD'],
        ['code' => '09', 'Muncity' => 'JOSEFINA'],
        ['code' => '09', 'Muncity' => 'PITOGO'],
        ['code' => '09', 'Muncity' => 'SOMINOT (DON MARIANO MARCOS)'],
        ['code' => '09', 'Muncity' => 'VINCENZO A. SAGUN'],
        ['code' => '09', 'Muncity' => 'GUIPOS'],
        ['code' => '09', 'Muncity' => 'TIGBAO'],
        ['code' => '09', 'Muncity' => 'ALICIA'],
        ['code' => '09', 'Muncity' => 'BUUG'],
        ['code' => '09', 'Muncity' => 'DIPLAHAN'],
        ['code' => '09', 'Muncity' => 'IMELDA'],
        ['code' => '09', 'Muncity' => 'IPIL'],
        ['code' => '09', 'Muncity' => 'KABASALAN'],
        ['code' => '09', 'Muncity' => 'MABUHAY'],
        ['code' => '09', 'Muncity' => 'MALANGAS'],
        ['code' => '09', 'Muncity' => 'NAGA'],
        ['code' => '09', 'Muncity' => 'OLUTANGA'],
        ['code' => '09', 'Muncity' => 'PAYAO'],
        ['code' => '09', 'Muncity' => 'ROSELLER LIM'],
        ['code' => '09', 'Muncity' => 'SIAY'],
        ['code' => '09', 'Muncity' => 'TALUSAN'],
        ['code' => '09', 'Muncity' => 'TITAY'],
        ['code' => '09', 'Muncity' => 'TUNGAWAN'],
        ['code' => '09', 'Muncity' => 'CITY OF ISABELA (Capital)'],
        ['code' => '10', 'Muncity' => 'BAUNGON'],
        ['code' => '10', 'Muncity' => 'DAMULOG'],
        ['code' => '10', 'Muncity' => 'DANGCAGAN'],
        ['code' => '10', 'Muncity' => 'DON CARLOS'],
        ['code' => '10', 'Muncity' => 'IMPASUG-ONG'],
        ['code' => '10', 'Muncity' => 'KADINGILAN'],
        ['code' => '10', 'Muncity' => 'KALILANGAN'],
        ['code' => '10', 'Muncity' => 'KIBAWE'],
        ['code' => '10', 'Muncity' => 'KITAOTAO'],
        ['code' => '10', 'Muncity' => 'LANTAPAN'],
        ['code' => '10', 'Muncity' => 'LIBONA'],
        ['code' => '10', 'Muncity' => 'CITY MALAYBALAY (Capital)'],
        ['code' => '10', 'Muncity' => 'MALITBOG'],
        ['code' => '10', 'Muncity' => 'MANOLO FORTICH'],
        ['code' => '10', 'Muncity' => 'MARAMAG'],
        ['code' => '10', 'Muncity' => 'PANGANTUCAN'],
        ['code' => '10', 'Muncity' => 'QUEZON'],
        ['code' => '10', 'Muncity' => 'SAN FERNANDO'],
        ['code' => '10', 'Muncity' => 'SUMILAO'],
        ['code' => '10', 'Muncity' => 'TALAKAG'],
        ['code' => '10', 'Muncity' => 'CITY OF VALENCIA'],
        ['code' => '10', 'Muncity' => 'CABANGLASAN'],
        ['code' => '10', 'Muncity' => 'CATARMAN'],
        ['code' => '10', 'Muncity' => 'GUINSILIBAN'],
        ['code' => '10', 'Muncity' => 'MAHINOG'],
        ['code' => '10', 'Muncity' => 'MAMBAJAO (Capital)'],
        ['code' => '10', 'Muncity' => 'SAGAY'],
        ['code' => '10', 'Muncity' => 'BACOLOD'],
        ['code' => '10', 'Muncity' => 'BALOI'],
        ['code' => '10', 'Muncity' => 'BAROY'],
        ['code' => '10', 'Muncity' => 'ILIGAN CITY'],
        ['code' => '10', 'Muncity' => 'KAPATAGAN'],
        ['code' => '10', 'Muncity' => 'SULTAN NAGA DIMAPORO (KAROMATAN)'],
        ['code' => '10', 'Muncity' => 'KAUSWAGAN'],
        ['code' => '10', 'Muncity' => 'KOLAMBUGAN'],
        ['code' => '10', 'Muncity' => 'LALA'],
        ['code' => '10', 'Muncity' => 'LINAMON'],
        ['code' => '10', 'Muncity' => 'MAGSAYSAY'],
        ['code' => '10', 'Muncity' => 'MAIGO'],
        ['code' => '10', 'Muncity' => 'MATUNGAO'],
        ['code' => '10', 'Muncity' => 'MUNAI'],
        ['code' => '10', 'Muncity' => 'NUNUNGAN'],
        ['code' => '10', 'Muncity' => 'PANTAO RAGAT'],
        ['code' => '10', 'Muncity' => 'POONA PIAGAPO'],
        ['code' => '10', 'Muncity' => 'SALVADOR'],
        ['code' => '10', 'Muncity' => 'SAPAD'],
        ['code' => '10', 'Muncity' => 'TAGOLOAN'],
        ['code' => '10', 'Muncity' => 'TANGCAL'],
        ['code' => '10', 'Muncity' => 'TUBOD (Capital)'],
        ['code' => '10', 'Muncity' => 'PANTAR'],
        ['code' => '10', 'Muncity' => 'ALORAN'],
        ['code' => '10', 'Muncity' => 'BALIANGAO'],
        ['code' => '10', 'Muncity' => 'BONIFACIO'],
        ['code' => '10', 'Muncity' => 'CALAMBA'],
        ['code' => '10', 'Muncity' => 'CLARIN'],
        ['code' => '10', 'Muncity' => 'CONCEPCION'],
        ['code' => '10', 'Muncity' => 'JIMENEZ'],
        ['code' => '10', 'Muncity' => 'LOPEZ JAENA'],
        ['code' => '10', 'Muncity' => 'OROQUIETA CITY (Capital)'],
        ['code' => '10', 'Muncity' => 'OZAMIS CITY'],
        ['code' => '10', 'Muncity' => 'PANAON'],
        ['code' => '10', 'Muncity' => 'PLAREL'],
        ['code' => '10', 'Muncity' => 'SAPANG DALAGA'],
        ['code' => '10', 'Muncity' => 'SINACABAN'],
        ['code' => '10', 'Muncity' => 'TANGUB CITY'],
        ['code' => '10', 'Muncity' => 'TUDELA'],
        ['code' => '10', 'Muncity' => 'DON VICTORIANO CHIONGBIAN'],
        ['code' => '10', 'Muncity' => 'ALUBIJ'],
        ['code' => '10', 'Muncity' => 'BALINGASAG'],
        ['code' => '10', 'Muncity' => 'BALINGOAN'],
        ['code' => '10', 'Muncity' => 'BINUANGAN'],
        ['code' => '10', 'Muncity' => 'CAGAYAN DE ORO CITY (Capital)'],
        ['code' => '10', 'Muncity' => 'CLAVERIA'],
        ['code' => '10', 'Muncity' => 'EL SALVADOR'],
        ['code' => '10', 'Muncity' => 'GINGOOG CITY'],
        ['code' => '10', 'Muncity' => 'GITAGUM'],
        ['code' => '10', 'Muncity' => 'INITAO'],
        ['code' => '10', 'Muncity' => 'JASAAN'],
        ['code' => '10', 'Muncity' => 'KINOGUITAN'],
        ['code' => '10', 'Muncity' => 'LAGONGLONG'],
        ['code' => '10', 'Muncity' => 'LAGUINDINGAN'],
        ['code' => '10', 'Muncity' => 'LIBERTAD'],
        ['code' => '10', 'Muncity' => 'LUGAIT'],
        ['code' => '10', 'Muncity' => 'MAGSAYSAY (LINUGOS)'],
        ['code' => '10', 'Muncity' => 'MANTICAO'],
        ['code' => '10', 'Muncity' => 'MEDINA'],
        ['code' => '10', 'Muncity' => 'NAAWAN'],
        ['code' => '10', 'Muncity' => 'OPOL'],
        ['code' => '10', 'Muncity' => 'SALAY'],
        ['code' => '10', 'Muncity' => 'SUGBONGCOGON'],
        ['code' => '10', 'Muncity' => 'TAGOLOAN'],
        ['code' => '10', 'Muncity' => 'TALISAYAN'],
        ['code' => '10', 'Muncity' => 'VILLANUEVA'],
        ['code' => '11', 'Muncity' => 'ASUNCION (SAUG)'],
        ['code' => '11', 'Muncity' => 'CARMEN'],
        ['code' => '11', 'Muncity' => 'KAPALONG'],
        ['code' => '11', 'Muncity' => 'NEW CORELLA'],
        ['code' => '11', 'Muncity' => 'CITY OF PANABO'],
        ['code' => '11', 'Muncity' => 'ISLAND GARDEN CITY OF SAMAL'],
        ['code' => '11', 'Muncity' => 'SANTO TOMAS'],
        ['code' => '11', 'Muncity' => 'CITY OF TAGUM (Capital)'],
        ['code' => '11', 'Muncity' => 'TALAINGOD'],
        ['code' => '11', 'Muncity' => 'BRAULIO E. DUJALI'],
        ['code' => '11', 'Muncity' => 'SAN ISRO'],
        ['code' => '11', 'Muncity' => 'BANSALAN'],
        ['code' => '11', 'Muncity' => 'DAVAO CITY'],
        ['code' => '11', 'Muncity' => 'CITY OF DIGOS (Capital)'],
        ['code' => '11', 'Muncity' => 'HAGONOY'],
        ['code' => '11', 'Muncity' => 'JOSE ABAD SANTOS (TRINAD)'],
        ['code' => '11', 'Muncity' => 'KIBLAWAN'],
        ['code' => '11', 'Muncity' => 'MAGSAYSAY'],
        ['code' => '11', 'Muncity' => 'MALALAG'],
        ['code' => '11', 'Muncity' => 'MALITA'],
        ['code' => '11', 'Muncity' => 'MATANAO'],
        ['code' => '11', 'Muncity' => 'PADADA'],
        ['code' => '11', 'Muncity' => 'SANTA CRUZ'],
        ['code' => '11', 'Muncity' => 'SANTA MARIA'],
        ['code' => '11', 'Muncity' => 'SULOP'],
        ['code' => '11', 'Muncity' => 'SARANGANI'],
        ['code' => '11', 'Muncity' => 'DON MARCELINO'],
        ['code' => '11', 'Muncity' => 'BAGANGA'],
        ['code' => '11', 'Muncity' => 'BANAYBANAY'],
        ['code' => '11', 'Muncity' => 'BOSTON'],
        ['code' => '11', 'Muncity' => 'CARAGA'],
        ['code' => '11', 'Muncity' => 'CATEEL'],
        ['code' => '11', 'Muncity' => 'GOVERNOR GENEROSO'],
        ['code' => '11', 'Muncity' => 'LUPON'],
        ['code' => '11', 'Muncity' => 'MANAY'],
        ['code' => '11', 'Muncity' => 'MATI (Capital)'],
        ['code' => '11', 'Muncity' => 'SAN ISRO'],
        ['code' => '11', 'Muncity' => 'TARRAGONA'],
        ['code' => '11', 'Muncity' => 'COMPOSTELA'],
        ['code' => '11', 'Muncity' => 'LAAK (SAN VICENTE)'],
        ['code' => '11', 'Muncity' => 'MABINI (DOÑA ALICIA)'],
        ['code' => '11', 'Muncity' => 'MACO'],
        ['code' => '11', 'Muncity' => 'MARAGUSAN (SAN MARIANO)'],
        ['code' => '11', 'Muncity' => 'MAWAB'],
        ['code' => '11', 'Muncity' => 'MONKAYO'],
        ['code' => '11', 'Muncity' => 'MONTEVISTA'],
        ['code' => '11', 'Muncity' => 'NABUNTURAN (Capital)'],
        ['code' => '11', 'Muncity' => 'NEW BATAAN'],
        ['code' => '11', 'Muncity' => 'PANTUKAN'],
        ['code' => '12', 'Muncity' => 'ALAMADA'],
        ['code' => '12', 'Muncity' => 'CARMEN'],
        ['code' => '12', 'Muncity' => 'KABACAN'],
        ['code' => '12', 'Muncity' => 'CITY OF KAPAWAN (Capital)'],
        ['code' => '12', 'Muncity' => 'LIBUNGAN'],
        ['code' => '12', 'Muncity' => 'MAGPET'],
        ['code' => '12', 'Muncity' => 'MAKILALA'],
        ['code' => '12', 'Muncity' => 'MATALAM'],
        ['code' => '12', 'Muncity' => 'MSAYAP'],
        ['code' => '12', 'Muncity' => 'M\'LANG'],
        ['code' => '12', 'Muncity' => 'PIGKAWAYAN'],
        ['code' => '12', 'Muncity' => 'PIKIT'],
        ['code' => '12', 'Muncity' => 'PRESENT ROXAS'],
        ['code' => '12', 'Muncity' => 'TULUNAN'],
        ['code' => '12', 'Muncity' => 'ANTIPAS'],
        ['code' => '12', 'Muncity' => 'BANISILAN'],
        ['code' => '12', 'Muncity' => 'ALEOSAN'],
        ['code' => '12', 'Muncity' => 'ARAKAN'],
        ['code' => '12', 'Muncity' => 'COTABATO CITY '],
        ['code' => '12', 'Muncity' => 'BANGA'],
        ['code' => '12', 'Muncity' => 'GENERAL SANTOS CITY (DADIANGAS)'],
        ['code' => '12', 'Muncity' => 'CITY OF KORONADAL (Capital)'],
        ['code' => '12', 'Muncity' => 'NORALA'],
        ['code' => '12', 'Muncity' => 'POLOMOLOK'],
        ['code' => '12', 'Muncity' => 'SURALLAH'],
        ['code' => '12', 'Muncity' => 'TAMPAKAN'],
        ['code' => '12', 'Muncity' => 'TANTANGAN'],
        ['code' => '12', 'Muncity' => 'T\'BOLI'],
        ['code' => '12', 'Muncity' => 'TUPI'],
        ['code' => '12', 'Muncity' => 'SANTO NIÑO'],
        ['code' => '12', 'Muncity' => 'LAKE SEBU'],
        ['code' => '12', 'Muncity' => 'BAGUMBAYAN'],
        ['code' => '12', 'Muncity' => 'COLUMBIO'],
        ['code' => '12', 'Muncity' => 'ESPERANZA'],
        ['code' => '12', 'Muncity' => 'ISULAN (Capital)'],
        ['code' => '12', 'Muncity' => 'KALAMANSIG'],
        ['code' => '12', 'Muncity' => 'LEBAK'],
        ['code' => '12', 'Muncity' => 'LUTAYAN'],
        ['code' => '12', 'Muncity' => 'LAMBAYONG (MARIANO MARCOS)'],
        ['code' => '12', 'Muncity' => 'PALIMBANG'],
        ['code' => '12', 'Muncity' => 'PRESENT QUIRINO'],
        ['code' => '12', 'Muncity' => 'CITY OF TACURONG'],
        ['code' => '12', 'Muncity' => 'SEN. NINOY AQUINO'],
        ['code' => '12', 'Muncity' => 'ALABEL (Capital)'],
        ['code' => '12', 'Muncity' => 'GLAN'],
        ['code' => '12', 'Muncity' => 'KIAMBA'],
        ['code' => '12', 'Muncity' => 'MAASIM'],
        ['code' => '12', 'Muncity' => 'MAITUM'],
        ['code' => '12', 'Muncity' => 'MALAPATAN'],
        ['code' => '12', 'Muncity' => 'MALUNGON'],
        ['code' => '12', 'Muncity' => 'COTABATO'],
        ['code' => '13', 'Muncity' => 'CITY OF MANILA'],
        ['code' => '13', 'Muncity' => 'TONDO'],
        ['code' => '13', 'Muncity' => 'BINONDO'],
        ['code' => '13', 'Muncity' => 'QUIAPO'],
        ['code' => '13', 'Muncity' => 'SAN NICOLAS'],
        ['code' => '13', 'Muncity' => 'SANTA CRUZ'],
        ['code' => '13', 'Muncity' => 'SAMPALOC'],
        ['code' => '13', 'Muncity' => 'SAN MIGUEL'],
        ['code' => '13', 'Muncity' => 'ERMITA'],
        ['code' => '13', 'Muncity' => 'INTRAMUROS'],
        ['code' => '13', 'Muncity' => 'MALATE'],
        ['code' => '13', 'Muncity' => 'PACO'],
        ['code' => '13', 'Muncity' => 'PANDACAN'],
        ['code' => '13', 'Muncity' => 'PORT AREA'],
        ['code' => '13', 'Muncity' => 'SANTA ANA'],
        ['code' => '13', 'Muncity' => 'CITY OF MANDALUYONG'],
        ['code' => '13', 'Muncity' => 'CITY OF MARIKINA'],
        ['code' => '13', 'Muncity' => 'CITY OF PASIG'],
        ['code' => '13', 'Muncity' => 'QUEZON CITY'],
        ['code' => '13', 'Muncity' => 'SAN JUAN'],
        ['code' => '13', 'Muncity' => 'KALOOKAN CITY'],
        ['code' => '13', 'Muncity' => 'CITY OF MALABON'],
        ['code' => '13', 'Muncity' => 'NAVOTAS'],
        ['code' => '13', 'Muncity' => 'CITY OF VALENZUELA'],
        ['code' => '13', 'Muncity' => 'CITY OF LAS PIÑAS'],
        ['code' => '13', 'Muncity' => 'CITY OF MAKATI'],
        ['code' => '13', 'Muncity' => 'CITY OF MUNTINLUPA'],
        ['code' => '13', 'Muncity' => 'CITY OF PARAÑAQUE'],
        ['code' => '13', 'Muncity' => 'PASAY CITY'],
        ['code' => '13', 'Muncity' => 'PATEROS'],
        ['code' => '13', 'Muncity' => 'TAGUIG'],
        ['code' => '14', 'Muncity' => 'BANGUED (Capital)'],
        ['code' => '14', 'Muncity' => 'BOLINEY'],
        ['code' => '14', 'Muncity' => 'BUCAY'],
        ['code' => '14', 'Muncity' => 'BUCLOC'],
        ['code' => '14', 'Muncity' => 'DAGUIOMAN'],
        ['code' => '14', 'Muncity' => 'DANGLAS'],
        ['code' => '14', 'Muncity' => 'DOLORES'],
        ['code' => '14', 'Muncity' => 'LA PAZ'],
        ['code' => '14', 'Muncity' => 'LACUB'],
        ['code' => '14', 'Muncity' => 'LAGANGILANG'],
        ['code' => '14', 'Muncity' => 'LAGAYAN'],
        ['code' => '14', 'Muncity' => 'LANGEN'],
        ['code' => '14', 'Muncity' => 'LICUAN-BAAY (LICUAN)'],
        ['code' => '14', 'Muncity' => 'LUBA'],
        ['code' => '14', 'Muncity' => 'MALIBCONG'],
        ['code' => '14', 'Muncity' => 'MANABO'],
        ['code' => '14', 'Muncity' => 'PEÑARRUBIA'],
        ['code' => '14', 'Muncity' => 'PIGAN'],
        ['code' => '14', 'Muncity' => 'PILAR'],
        ['code' => '14', 'Muncity' => 'SALLAPADAN'],
        ['code' => '14', 'Muncity' => 'SAN ISRO'],
        ['code' => '14', 'Muncity' => 'SAN JUAN'],
        ['code' => '14', 'Muncity' => 'SAN QUINTIN'],
        ['code' => '14', 'Muncity' => 'TAYUM'],
        ['code' => '14', 'Muncity' => 'TINEG'],
        ['code' => '14', 'Muncity' => 'TUBO'],
        ['code' => '14', 'Muncity' => 'VILLAVICIOSA'],
        ['code' => '14', 'Muncity' => 'ATOK'],
        ['code' => '14', 'Muncity' => 'BAGUIO CITY'],
        ['code' => '14', 'Muncity' => 'BAKUN'],
        ['code' => '14', 'Muncity' => 'BOKOD'],
        ['code' => '14', 'Muncity' => 'BUGUIAS'],
        ['code' => '14', 'Muncity' => 'ITOGON'],
        ['code' => '14', 'Muncity' => 'KABAYAN'],
        ['code' => '14', 'Muncity' => 'KAPANGAN'],
        ['code' => '14', 'Muncity' => 'KIBUNGAN'],
        ['code' => '14', 'Muncity' => 'LA TRINAD (Capital)'],
        ['code' => '14', 'Muncity' => 'MANKAYAN'],
        ['code' => '14', 'Muncity' => 'SABLAN'],
        ['code' => '14', 'Muncity' => 'TUBA'],
        ['code' => '14', 'Muncity' => 'TUBLAY'],
        ['code' => '14', 'Muncity' => 'BANAUE'],
        ['code' => '14', 'Muncity' => 'HUNGDUAN'],
        ['code' => '14', 'Muncity' => 'KIANGAN'],
        ['code' => '14', 'Muncity' => 'LAGAWE (Capital)'],
        ['code' => '14', 'Muncity' => 'LAMUT'],
        ['code' => '14', 'Muncity' => 'MAYOYAO'],
        ['code' => '14', 'Muncity' => 'ALFONSO LISTA (POTIA)'],
        ['code' => '14', 'Muncity' => 'AGUINALDO'],
        ['code' => '14', 'Muncity' => 'HINGYON'],
        ['code' => '14', 'Muncity' => 'TINOC'],
        ['code' => '14', 'Muncity' => 'ASIPULO'],
        ['code' => '14', 'Muncity' => 'BALBALAN'],
        ['code' => '14', 'Muncity' => 'LUBUAGAN'],
        ['code' => '14', 'Muncity' => 'PASIL'],
        ['code' => '14', 'Muncity' => 'PINUKPUK'],
        ['code' => '14', 'Muncity' => 'RIZAL (LIWAN)'],
        ['code' => '14', 'Muncity' => 'TABUK (Capital)'],
        ['code' => '14', 'Muncity' => 'TANUDAN'],
        ['code' => '14', 'Muncity' => 'TINGLAYAN'],
        ['code' => '14', 'Muncity' => 'BARLIG'],
        ['code' => '14', 'Muncity' => 'BAUKO'],
        ['code' => '14', 'Muncity' => 'BESAO'],
        ['code' => '14', 'Muncity' => 'BONTOC (Capital)'],
        ['code' => '14', 'Muncity' => 'NATONIN'],
        ['code' => '14', 'Muncity' => 'PARACELIS'],
        ['code' => '14', 'Muncity' => 'SABANGAN'],
        ['code' => '14', 'Muncity' => 'SADANGA'],
        ['code' => '14', 'Muncity' => 'SAGADA'],
        ['code' => '14', 'Muncity' => 'TADIAN'],
        ['code' => '14', 'Muncity' => 'CALANASAN (BAYAG)'],
        ['code' => '14', 'Muncity' => 'CONNER'],
        ['code' => '14', 'Muncity' => 'FLORA'],
        ['code' => '14', 'Muncity' => 'KABUGAO (Capital)'],
        ['code' => '14', 'Muncity' => 'LUNA'],
        ['code' => '14', 'Muncity' => 'PUDTOL'],
        ['code' => '14', 'Muncity' => 'SANTA MARCELA'],
        ['code' => '15', 'Muncity' => 'LAMITAN'],
        ['code' => '15', 'Muncity' => 'LANTAWAN'],
        ['code' => '15', 'Muncity' => 'MALUSO'],
        ['code' => '15', 'Muncity' => 'SUMISIP'],
        ['code' => '15', 'Muncity' => 'TIPO-TIPO'],
        ['code' => '15', 'Muncity' => 'TUBURAN'],
        ['code' => '15', 'Muncity' => 'AKBAR'],
        ['code' => '15', 'Muncity' => 'AL-BARKA'],
        ['code' => '15', 'Muncity' => 'HADJI MOHAMMAD AJUL'],
        ['code' => '15', 'Muncity' => 'UNGKAYA PUKAN'],
        ['code' => '15', 'Muncity' => 'HADJI MUHTAMAD'],
        ['code' => '15', 'Muncity' => 'BACOLOD-KALAWI (BACOLOD GRANDE)'],
        ['code' => '15', 'Muncity' => 'BALABAGAN'],
        ['code' => '15', 'Muncity' => 'BALINDONG (WATU)'],
        ['code' => '15', 'Muncity' => 'BAYANG'],
        ['code' => '15', 'Muncity' => 'BINAYAN'],
        ['code' => '15', 'Muncity' => 'BUBONG'],
        ['code' => '15', 'Muncity' => 'BUTIG'],
        ['code' => '15', 'Muncity' => 'GANASSI'],
        ['code' => '15', 'Muncity' => 'KAPAI'],
        ['code' => '15', 'Muncity' => 'LUMBA-BAYABAO (MAGUING)'],
        ['code' => '15', 'Muncity' => 'LUMBATAN'],
        ['code' => '15', 'Muncity' => 'MADALUM'],
        ['code' => '15', 'Muncity' => 'MADAMBA'],
        ['code' => '15', 'Muncity' => 'MALABANG'],
        ['code' => '15', 'Muncity' => 'MARANTAO'],
        ['code' => '15', 'Muncity' => 'MARAWI CITY'],
        ['code' => '15', 'Muncity' => 'MASIU'],
        ['code' => '15', 'Muncity' => 'MULONDO'],
        ['code' => '15', 'Muncity' => 'PAGAYAWAN (TATARIKAN)'],
        ['code' => '15', 'Muncity' => 'PIAGAPO'],
        ['code' => '15', 'Muncity' => 'POONA BAYABAO (GATA)'],
        ['code' => '15', 'Muncity' => 'PUALAS'],
        ['code' => '15', 'Muncity' => 'DITSAAN-RAMAIN'],
        ['code' => '15', 'Muncity' => 'SAGUIARAN'],
        ['code' => '15', 'Muncity' => 'TAMPARAN'],
        ['code' => '15', 'Muncity' => 'TARAKA'],
        ['code' => '15', 'Muncity' => 'TUBARAN'],
        ['code' => '15', 'Muncity' => 'TUGAYA'],
        ['code' => '15', 'Muncity' => 'WAO'],
        ['code' => '15', 'Muncity' => 'MAROGONG'],
        ['code' => '15', 'Muncity' => 'CALANOGAS'],
        ['code' => '15', 'Muncity' => 'BUADIPOSO-BUNTONG'],
        ['code' => '15', 'Muncity' => 'MAGUING'],
        ['code' => '15', 'Muncity' => 'SULTAN GUMANDER'],
        ['code' => '15', 'Muncity' => 'LUMBAYANAGUE'],
        ['code' => '15', 'Muncity' => 'BUMBARAN'],
        ['code' => '15', 'Muncity' => 'TAGOLOAN II'],
        ['code' => '15', 'Muncity' => 'KAPATAGAN'],
        ['code' => '15', 'Muncity' => 'SULTAN DUMALONDONG'],
        ['code' => '15', 'Muncity' => 'LUMBACA-UNAYAN'],
        ['code' => '15', 'Muncity' => 'AMPATUAN'],
        ['code' => '15', 'Muncity' => 'BULDON'],
        ['code' => '15', 'Muncity' => 'BULUAN'],
        ['code' => '15', 'Muncity' => 'DATU PAGLAS'],
        ['code' => '15', 'Muncity' => 'DATU PIANG'],
        ['code' => '15', 'Muncity' => 'DATU ODIN SINSUAT (DINAIG)'],
        ['code' => '15', 'Muncity' => 'SHARIFF AGUAK (MAGANOY) (Capital)'],
        ['code' => '15', 'Muncity' => 'MATANOG'],
        ['code' => '15', 'Muncity' => 'PAGALUNGAN'],
        ['code' => '15', 'Muncity' => 'PARANG'],
        ['code' => '15', 'Muncity' => 'SULTAN KUDARAT (NULING)'],
        ['code' => '15', 'Muncity' => 'SULTAN SA BARONGIS (LAMBAYONG)'],
        ['code' => '15', 'Muncity' => 'KABUNTALAN (TUMBAO)'],
        ['code' => '15', 'Muncity' => 'UPI'],
        ['code' => '15', 'Muncity' => 'TALAYAN'],
        ['code' => '15', 'Muncity' => 'SOUTH UPI'],
        ['code' => '15', 'Muncity' => 'BARIRA'],
        ['code' => '15', 'Muncity' => 'GEN. S. K. PENDATUN'],
        ['code' => '15', 'Muncity' => 'MAMASAPANO'],
        ['code' => '15', 'Muncity' => 'TALITAY'],
        ['code' => '15', 'Muncity' => 'PAGAGAWAN'],
        ['code' => '15', 'Muncity' => 'PAGLAT'],
        ['code' => '15', 'Muncity' => 'SULTAN MASTURA'],
        ['code' => '15', 'Muncity' => 'GUINDULUNGAN'],
        ['code' => '15', 'Muncity' => 'DATU SAUDI-AMPATUAN'],
        ['code' => '15', 'Muncity' => 'DATU UNSAY'],
        ['code' => '15', 'Muncity' => 'DATU ABDULLAH SANGKI'],
        ['code' => '15', 'Muncity' => 'RAJAH BUAYAN'],
        ['code' => '15', 'Muncity' => 'DATU ANGGAL MTIMBANG'],
        ['code' => '15', 'Muncity' => 'MANGUDADATU'],
        ['code' => '15', 'Muncity' => 'PANDAG'],
        ['code' => '15', 'Muncity' => 'INDANAN'],
        ['code' => '15', 'Muncity' => 'JOLO (Capital)'],
        ['code' => '15', 'Muncity' => 'KALINGALAN CALUANG'],
        ['code' => '15', 'Muncity' => 'LUUK'],
        ['code' => '15', 'Muncity' => 'MAIMBUNG'],
        ['code' => '15', 'Muncity' => 'HADJI PANGLIMA TAHIL (MARUNGGAS)'],
        ['code' => '15', 'Muncity' => 'OLD PANAMAO'],
        ['code' => '15', 'Muncity' => 'PANGUTARAN'],
        ['code' => '15', 'Muncity' => 'PARANG'],
        ['code' => '15', 'Muncity' => 'PATA'],
        ['code' => '15', 'Muncity' => 'PATIKUL'],
        ['code' => '15', 'Muncity' => 'SIASI'],
        ['code' => '15', 'Muncity' => 'TALIPAO'],
        ['code' => '15', 'Muncity' => 'TAPUL'],
        ['code' => '15', 'Muncity' => 'TONGKIL'],
        ['code' => '15', 'Muncity' => 'PANGLIMA ESTINO (NEW PANAMAO)'],
        ['code' => '15', 'Muncity' => 'LUGUS'],
        ['code' => '15', 'Muncity' => 'PANDAMI'],
        ['code' => '15', 'Muncity' => 'OMAR'],
        ['code' => '15', 'Muncity' => 'PANGLIMA SUGALA (BALIMBING) (Capital)'],
        ['code' => '15', 'Muncity' => 'BONGAO'],
        ['code' => '15', 'Muncity' => 'MAPUN (CAGAYAN DE TAWI-TAWI)'],
        ['code' => '15', 'Muncity' => 'SIMUNUL'],
        ['code' => '15', 'Muncity' => 'SITANGKAI'],
        ['code' => '15', 'Muncity' => 'SOUTH UBIAN'],
        ['code' => '15', 'Muncity' => 'TANDUBAS'],
        ['code' => '15', 'Muncity' => 'TURTLE ISLANDS'],
        ['code' => '15', 'Muncity' => 'LANGUYAN'],
        ['code' => '15', 'Muncity' => 'SAPA-SAPA'],
        ['code' => '15', 'Muncity' => 'SIBUTU'],
        ['code' => '15', 'Muncity' => 'BARIRA'],
        ['code' => '15', 'Muncity' => 'BULDON'],
        ['code' => '15', 'Muncity' => 'DATU BLAH T. SINSUAT'],
        ['code' => '15', 'Muncity' => 'DATU ODIN SINSUAT (DINAIG) (Capital)'],
        ['code' => '15', 'Muncity' => 'KABUNTALAN (TUMBAO)'],
        ['code' => '15', 'Muncity' => 'MATANOG'],
        ['code' => '15', 'Muncity' => 'PARANG'],
        ['code' => '15', 'Muncity' => 'SULTAN KUDARAT (NULING)'],
        ['code' => '15', 'Muncity' => 'SULTAN MASTURA'],
        ['code' => '15', 'Muncity' => 'UPI'],
        ['code' => '15', 'Muncity' => 'NORTHERN KABUNTALAN'],
        ['code' => '16', 'Muncity' => 'BUENAVISTA'],
        ['code' => '16', 'Muncity' => 'BUTUAN CITY (Capital)'],
        ['code' => '16', 'Muncity' => 'CITY OF CABADBARAN'],
        ['code' => '16', 'Muncity' => 'CARMEN'],
        ['code' => '16', 'Muncity' => 'JABONGA'],
        ['code' => '16', 'Muncity' => 'KITCHARAO'],
        ['code' => '16', 'Muncity' => 'LAS NIEVES'],
        ['code' => '16', 'Muncity' => 'MAGALLANES'],
        ['code' => '16', 'Muncity' => 'NASIPIT'],
        ['code' => '16', 'Muncity' => 'SANTIAGO'],
        ['code' => '16', 'Muncity' => 'TUBAY'],
        ['code' => '16', 'Muncity' => 'REMEDIOS T. ROMUALDEZ'],
        ['code' => '16', 'Muncity' => 'CITY OF BAYUGAN'],
        ['code' => '16', 'Muncity' => 'BUNAWAN'],
        ['code' => '16', 'Muncity' => 'ESPERANZA'],
        ['code' => '16', 'Muncity' => 'LA PAZ'],
        ['code' => '16', 'Muncity' => 'LORETO'],
        ['code' => '16', 'Muncity' => 'PROSPERAD (Capital)'],
        ['code' => '16', 'Muncity' => 'ROSARIO'],
        ['code' => '16', 'Muncity' => 'SAN FRANCISCO'],
        ['code' => '16', 'Muncity' => 'SAN LUIS'],
        ['code' => '16', 'Muncity' => 'SANTA JOSEFA'],
        ['code' => '16', 'Muncity' => 'TALACOGON'],
        ['code' => '16', 'Muncity' => 'TRENTO'],
        ['code' => '16', 'Muncity' => 'VERUELA'],
        ['code' => '16', 'Muncity' => 'SIBAGAT'],
        ['code' => '16', 'Muncity' => 'ALEGRIA'],
        ['code' => '16', 'Muncity' => 'BACUAG'],
        ['code' => '16', 'Muncity' => '(UNKNOWN)'],
        ['code' => '16', 'Muncity' => 'BURGOS'],
        ['code' => '16', 'Muncity' => '(UNKNOWN)'],
        ['code' => '16', 'Muncity' => 'CLAVER'],
        ['code' => '16', 'Muncity' => 'DAPA'],
        ['code' => '16', 'Muncity' => 'DEL CARMEN'],
        ['code' => '16', 'Muncity' => '(UNKNOWN)'],
        ['code' => '16', 'Muncity' => 'GENERAL LUNA'],
        ['code' => '16', 'Muncity' => 'GIGAQUIT'],
        ['code' => '16', 'Muncity' => '(UNKNOWN)'],
        ['code' => '16', 'Muncity' => '(UNKNOWN)'],
        ['code' => '16', 'Muncity' => 'MAINIT'],
        ['code' => '16', 'Muncity' => 'MALIMONO'],
        ['code' => '16', 'Muncity' => 'PILAR'],
        ['code' => '16', 'Muncity' => 'PLACER'],
        ['code' => '16', 'Muncity' => 'SAN BENITO'],
        ['code' => '16', 'Muncity' => 'SAN FRANCISCO (ANAO-AON)'],
        ['code' => '16', 'Muncity' => 'SAN ISRO'],
        ['code' => '16', 'Muncity' => 'SANTA MONICA (SAPAO)'],
        ['code' => '16', 'Muncity' => 'SISON'],
        ['code' => '16', 'Muncity' => 'SOCORRO'],
        ['code' => '16', 'Muncity' => 'SURIGAO CITY (Capital)'],
        ['code' => '16', 'Muncity' => 'TAGANA-AN'],
        ['code' => '16', 'Muncity' => '(UNKNOWN)'],
        ['code' => '16', 'Muncity' => 'TUBOD'],
        ['code' => '16', 'Muncity' => '(UNKNOWN)'],
        ['code' => '16', 'Muncity' => 'BAROBO'],
        ['code' => '16', 'Muncity' => 'BAYABAS'],
        ['code' => '16', 'Muncity' => 'CITY OF BISLIG'],
        ['code' => '16', 'Muncity' => 'CAGWAIT'],
        ['code' => '16', 'Muncity' => 'CANTILAN'],
        ['code' => '16', 'Muncity' => 'CARMEN'],
        ['code' => '16', 'Muncity' => 'CARRASCAL'],
        ['code' => '16', 'Muncity' => 'CORTES'],
        ['code' => '16', 'Muncity' => 'HINATUAN'],
        ['code' => '16', 'Muncity' => 'LANUZA'],
        ['code' => '16', 'Muncity' => 'LIANGA'],
        ['code' => '16', 'Muncity' => 'LINGIG'],
        ['code' => '16', 'Muncity' => 'MADR'],
        ['code' => '16', 'Muncity' => 'MARIHATAG'],
        ['code' => '16', 'Muncity' => 'SAN AGUSTIN'],
        ['code' => '16', 'Muncity' => 'SAN MIGUEL'],
        ['code' => '16', 'Muncity' => 'TAGBINA'],
        ['code' => '16', 'Muncity' => 'TAGO'],
        ['code' => '16', 'Muncity' => 'CITY OF TANDAG (Capital)'],
        ['code' => '16', 'Muncity' => 'BASILISA (RIZAL)'],
        ['code' => '16', 'Muncity' => 'CAGDIANAO'],
        ['code' => '16', 'Muncity' => 'DINAGAT'],
        ['code' => '16', 'Muncity' => 'LIBJO (ALBOR)'],
        ['code' => '16', 'Muncity' => 'LORETO'],
        ['code' => '16', 'Muncity' => 'SAN JOSE (Capital)'],
        ['code' => '16', 'Muncity' => 'TUBAJON'],
        ['code' => '17', 'Muncity' => 'BOAC (Capital)'],
        ['code' => '17', 'Muncity' => 'BUENAVISTA'],
        ['code' => '17', 'Muncity' => 'GASAN'],
        ['code' => '17', 'Muncity' => 'MOGPOG'],
        ['code' => '17', 'Muncity' => 'SANTA CRUZ'],
        ['code' => '17', 'Muncity' => 'TORRIJOS'],
        ['code' => '17', 'Muncity' => 'ABRA DE ILOG'],
        ['code' => '17', 'Muncity' => 'CALINTAAN'],
        ['code' => '17', 'Muncity' => 'LOOC'],
        ['code' => '17', 'Muncity' => 'LUBANG'],
        ['code' => '17', 'Muncity' => 'MAGSAYSAY'],
        ['code' => '17', 'Muncity' => 'MAMBURAO (Capital)'],
        ['code' => '17', 'Muncity' => 'PALUAN'],
        ['code' => '17', 'Muncity' => 'RIZAL'],
        ['code' => '17', 'Muncity' => 'SABLAYAN'],
        ['code' => '17', 'Muncity' => 'SAN JOSE'],
        ['code' => '17', 'Muncity' => 'SANTA CRUZ'],
        ['code' => '17', 'Muncity' => 'BACO'],
        ['code' => '17', 'Muncity' => 'BANSUD'],
        ['code' => '17', 'Muncity' => 'BONGABONG'],
        ['code' => '17', 'Muncity' => 'BULALACAO (SAN PEDRO)'],
        ['code' => '17', 'Muncity' => 'CITY OF CALAPAN (Capital)'],
        ['code' => '17', 'Muncity' => 'GLORIA'],
        ['code' => '17', 'Muncity' => 'MANSALAY'],
        ['code' => '17', 'Muncity' => 'NAUJAN'],
        ['code' => '17', 'Muncity' => 'PINAMALAYAN'],
        ['code' => '17', 'Muncity' => 'POLA'],
        ['code' => '17', 'Muncity' => 'PUERTO GALERA'],
        ['code' => '17', 'Muncity' => 'ROXAS'],
        ['code' => '17', 'Muncity' => 'SAN TEODORO'],
        ['code' => '17', 'Muncity' => 'SOCORRO'],
        ['code' => '17', 'Muncity' => 'VICTORIA'],
        ['code' => '17', 'Muncity' => 'ABORLAN'],
        ['code' => '17', 'Muncity' => 'AGUTAYA'],
        ['code' => '17', 'Muncity' => 'ARACELI'],
        ['code' => '17', 'Muncity' => 'BALABAC'],
        ['code' => '17', 'Muncity' => 'BATARAZA'],
        ['code' => '17', 'Muncity' => 'BROOKE\'S POINT'],
        ['code' => '17', 'Muncity' => 'BUSUANGA'],
        ['code' => '17', 'Muncity' => 'CAGAYANCILLO'],
        ['code' => '17', 'Muncity' => 'CORON'],
        ['code' => '17', 'Muncity' => 'CUYO'],
        ['code' => '17', 'Muncity' => 'DUMARAN'],
        ['code' => '17', 'Muncity' => 'EL NO (BACUIT)'],
        ['code' => '17', 'Muncity' => 'LINAPACAN'],
        ['code' => '17', 'Muncity' => 'MAGSAYSAY'],
        ['code' => '17', 'Muncity' => 'NARRA'],
        ['code' => '17', 'Muncity' => 'PUERTO PRINCESA CITY (Capital)'],
        ['code' => '17', 'Muncity' => 'QUEZON'],
        ['code' => '17', 'Muncity' => 'ROXAS'],
        ['code' => '17', 'Muncity' => 'SAN VICENTE'],
        ['code' => '17', 'Muncity' => 'TAYTAY'],
        ['code' => '17', 'Muncity' => 'KALAYAAN'],
        ['code' => '17', 'Muncity' => 'CULION'],
        ['code' => '17', 'Muncity' => 'RIZAL (MARCOS)'],
        ['code' => '17', 'Muncity' => 'SOFRONIO ESPAÑOLA'],
        ['code' => '17', 'Muncity' => 'ALCANTARA'],
        ['code' => '17', 'Muncity' => 'BANTON'],
        ['code' => '17', 'Muncity' => 'CAJIOCAN'],
        ['code' => '17', 'Muncity' => 'CALATRAVA'],
        ['code' => '17', 'Muncity' => 'CONCEPCION'],
        ['code' => '17', 'Muncity' => 'CORCUERA'],
        ['code' => '17', 'Muncity' => 'LOOC'],
        ['code' => '17', 'Muncity' => 'MAGDIWANG'],
        ['code' => '17', 'Muncity' => 'ODIONGAN'],
        ['code' => '17', 'Muncity' => 'ROMBLON (Capital)'],
        ['code' => '17', 'Muncity' => 'SAN AGUSTIN'],
        ['code' => '17', 'Muncity' => 'SAN ANDRES'],
        ['code' => '17', 'Muncity' => 'SAN FERNANDO'],
        ['code' => '17', 'Muncity' => 'SAN JOSE'],
        ['code' => '17', 'Muncity' => 'SANTA FE'],
        ['code' => '17', 'Muncity' => 'FERROL'],
        ['code' => '17', 'Muncity' => 'SANTA MARIA (IMELDA)'],
        ['code' => '18', 'Muncity' => 'BACOLOD CITY (Capital)'],
        ['code' => '18', 'Muncity' => 'BAGO CITY'],
        ['code' => '18', 'Muncity' => 'BINALBAGAN'],
        ['code' => '18', 'Muncity' => 'CADIZ CITY'],
        ['code' => '18', 'Muncity' => 'CALATRAVA'],
        ['code' => '18', 'Muncity' => 'CANDONI'],
        ['code' => '18', 'Muncity' => 'CAUAYAN'],
        ['code' => '18', 'Muncity' => 'ENRIQUE B. MAGALONA (SARAVIA)'],
        ['code' => '18', 'Muncity' => 'CITY OF ESCALANTE'],
        ['code' => '18', 'Muncity' => 'CITY OF HIMAMAYLAN'],
        ['code' => '18', 'Muncity' => 'HINIGARAN'],
        ['code' => '18', 'Muncity' => 'HINOBA-AN (ASIA)'],
        ['code' => '18', 'Muncity' => 'ILOG'],
        ['code' => '18', 'Muncity' => 'ISABELA'],
        ['code' => '18', 'Muncity' => 'CITY OF KABANKALAN'],
        ['code' => '18', 'Muncity' => 'LA CARLOTA CITY'],
        ['code' => '18', 'Muncity' => 'LA CASTELLANA'],
        ['code' => '18', 'Muncity' => 'MANAPLA'],
        ['code' => '18', 'Muncity' => 'MOISES PADILLA (MAGALLON)'],
        ['code' => '18', 'Muncity' => 'MURCIA'],
        ['code' => '18', 'Muncity' => 'PONTEVEDRA'],
        ['code' => '18', 'Muncity' => 'PULUPANDAN'],
        ['code' => '18', 'Muncity' => 'SAGAY CITY'],
        ['code' => '18', 'Muncity' => 'SAN CARLOS CITY'],
        ['code' => '18', 'Muncity' => 'SAN ENRIQUE'],
        ['code' => '18', 'Muncity' => 'SILAY CITY'],
        ['code' => '18', 'Muncity' => 'CITY OF SIPALAY'],
        ['code' => '18', 'Muncity' => 'CITY OF TALISAY'],
        ['code' => '18', 'Muncity' => 'TOBOSO'],
        ['code' => '18', 'Muncity' => 'VALLADOL'],
        ['code' => '18', 'Muncity' => 'CITY OF VICTORIAS'],
        ['code' => '18', 'Muncity' => 'SALVADOR BENEDICTO'],
        ['code' => '18', 'Muncity' => 'AMLAN (AYUQUITAN)'],
        ['code' => '18', 'Muncity' => 'AYUNGON'],
        ['code' => '18', 'Muncity' => 'BACONG'],
        ['code' => '18', 'Muncity' => 'BAIS CITY'],
        ['code' => '18', 'Muncity' => 'BASAY'],
        ['code' => '18', 'Muncity' => 'CITY OF BAYAWAN (TULONG)'],
        ['code' => '18', 'Muncity' => 'BINDOY (PAYABON)'],
        ['code' => '18', 'Muncity' => 'CANLAON CITY'],
        ['code' => '18', 'Muncity' => 'DAUIN'],
        ['code' => '18', 'Muncity' => 'DUMAGUETE CITY (Capital)'],
        ['code' => '18', 'Muncity' => 'GUIHULNGAN'],
        ['code' => '18', 'Muncity' => 'JIMALALUD'],
        ['code' => '18', 'Muncity' => 'LA LIBERTAD'],
        ['code' => '18', 'Muncity' => 'MABINAY'],
        ['code' => '18', 'Muncity' => 'MANJUYOD'],
        ['code' => '18', 'Muncity' => 'PAMPLONA'],
        ['code' => '18', 'Muncity' => 'SAN JOSE'],
        ['code' => '18', 'Muncity' => 'SANTA CATALINA'],
        ['code' => '18', 'Muncity' => 'SIATON'],
        ['code' => '18', 'Muncity' => 'SIBULAN'],
        ['code' => '18', 'Muncity' => 'CITY OF TANJAY'],
        ['code' => '18', 'Muncity' => 'TAYASAN'],
        ['code' => '18', 'Muncity' => 'VALENCIA (LUZURRIAGA)'],
        ['code' => '18', 'Muncity' => 'VALLEHERMOSO'],
        ['code' => '18', 'Muncity' => 'ZAMBOANGUITA']
      ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return vo
     */
    public function down()
    {
        // Schema::table('lib_muncity', function($table) {
        //   $table->dropForeign('lib_muncity_region_code_foreign');
        //   $table->dropForeign('lib_muncity_province_code_foreign');
        // });
        Schema::drop('muncity');
    }
}
